/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.9.5
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QGridLayout>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLCDNumber>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QLabel *label_4;
    QLabel *label_2;
    QLabel *label;
    QWidget *layoutWidget;
    QGridLayout *gridLayout;
    QPushButton *select_range_1;
    QPushButton *button_clear_1;
    QLineEdit *range_1;
    QLCDNumber *win_1;
    QWidget *layoutWidget1;
    QGridLayout *gridLayout_2;
    QPushButton *select_range_2;
    QPushButton *button_clear_2;
    QLineEdit *range_2;
    QLCDNumber *win_2;
    QWidget *layoutWidget2;
    QGridLayout *gridLayout_3;
    QPushButton *select_range_3;
    QPushButton *button_clear_3;
    QLineEdit *range_3;
    QLCDNumber *win_3;
    QWidget *layoutWidget3;
    QGridLayout *gridLayout_4;
    QPushButton *select_range_4;
    QPushButton *button_clear_4;
    QLineEdit *range_4;
    QLCDNumber *win_4;
    QWidget *layoutWidget4;
    QGridLayout *gridLayout_5;
    QPushButton *select_range_5;
    QPushButton *button_clear_5;
    QLineEdit *range_5;
    QLCDNumber *win_5;
    QWidget *layoutWidget5;
    QGridLayout *gridLayout_6;
    QLineEdit *range_6;
    QPushButton *button_clear_6;
    QPushButton *select_range_6;
    QLCDNumber *win_6;
    QPushButton *card_3a;
    QPushButton *card_29;
    QPushButton *card_35;
    QPushButton *card_0d;
    QPushButton *card_3b;
    QPushButton *card_12;
    QPushButton *card_04;
    QPushButton *card_03;
    QPushButton *card_0c;
    QPushButton *card_33;
    QPushButton *card_37;
    QPushButton *card_26;
    QPushButton *card_0a;
    QPushButton *card_2e;
    QPushButton *card_1d;
    QPushButton *card_0e;
    QPushButton *card_36;
    QPushButton *card_3e;
    QPushButton *card_2a;
    QPushButton *card_24;
    QPushButton *card_3d;
    QPushButton *card_38;
    QPushButton *card_1c;
    QPushButton *card_0b;
    QPushButton *card_14;
    QPushButton *card_19;
    QPushButton *card_17;
    QPushButton *card_09;
    QPushButton *card_13;
    QPushButton *button_calculate;
    QPushButton *card_1b;
    QPushButton *card_34;
    QPushButton *card_23;
    QPushButton *card_02;
    QPushButton *card_18;
    QPushButton *card_08;
    QPushButton *card_06;
    QPushButton *card_3c;
    QPushButton *card_07;
    QPushButton *card_28;
    QPushButton *card_1e;
    QPushButton *card_25;
    QPushButton *card_22;
    QPushButton *card_2c;
    QPushButton *card_16;
    QPushButton *card_2b;
    QPushButton *card_32;
    QPushButton *card_05;
    QPushButton *card_2d;
    QPushButton *card_15;
    QPushButton *card_27;
    QPushButton *card_1a;
    QPushButton *button_clear_0;
    QPushButton *card_39;
    QPushButton *board_0;
    QPushButton *board_1;
    QPushButton *board_2;
    QPushButton *board_3;
    QPushButton *board_4;
    QPushButton *button_clear_all;
    QStatusBar *statusBar;
    QMenuBar *menuBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(406, 354);
        QSizePolicy sizePolicy(QSizePolicy::Fixed, QSizePolicy::Fixed);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(MainWindow->sizePolicy().hasHeightForWidth());
        MainWindow->setSizePolicy(sizePolicy);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        label_4 = new QLabel(centralWidget);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(13, 192, 171, 20));
        QFont font;
        font.setPointSize(7);
        label_4->setFont(font);
        label_2 = new QLabel(centralWidget);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(330, 10, 61, 20));
        label_2->setFont(font);
        label_2->setAlignment(Qt::AlignCenter);
        label = new QLabel(centralWidget);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(70, 10, 251, 16));
        label->setFont(font);
        layoutWidget = new QWidget(centralWidget);
        layoutWidget->setObjectName(QStringLiteral("layoutWidget"));
        layoutWidget->setGeometry(QRect(11, 25, 379, 26));
        gridLayout = new QGridLayout(layoutWidget);
        gridLayout->setSpacing(6);
        gridLayout->setContentsMargins(11, 11, 11, 11);
        gridLayout->setObjectName(QStringLiteral("gridLayout"));
        gridLayout->setHorizontalSpacing(3);
        gridLayout->setContentsMargins(0, 0, 0, 0);
        select_range_1 = new QPushButton(layoutWidget);
        select_range_1->setObjectName(QStringLiteral("select_range_1"));
        QIcon icon;
        icon.addFile(QStringLiteral(":/styles/icon_cards_yellow_32x32.png"), QSize(), QIcon::Normal, QIcon::Off);
        select_range_1->setIcon(icon);
        select_range_1->setIconSize(QSize(16, 16));

        gridLayout->addWidget(select_range_1, 0, 0, 1, 1);

        button_clear_1 = new QPushButton(layoutWidget);
        button_clear_1->setObjectName(QStringLiteral("button_clear_1"));
        QIcon icon1;
        icon1.addFile(QStringLiteral(":/styles/icon_cancel_32x32_round.png"), QSize(), QIcon::Normal, QIcon::Off);
        button_clear_1->setIcon(icon1);
        button_clear_1->setIconSize(QSize(16, 16));

        gridLayout->addWidget(button_clear_1, 0, 1, 1, 1);

        range_1 = new QLineEdit(layoutWidget);
        range_1->setObjectName(QStringLiteral("range_1"));
        range_1->setFont(font);
        range_1->setMaxLength(3700);

        gridLayout->addWidget(range_1, 0, 2, 1, 1);

        win_1 = new QLCDNumber(layoutWidget);
        win_1->setObjectName(QStringLiteral("win_1"));
        QFont font1;
        font1.setKerning(true);
        win_1->setFont(font1);
        win_1->setStyleSheet(QStringLiteral(""));
        win_1->setFrameShape(QFrame::StyledPanel);
        win_1->setSmallDecimalPoint(true);
        win_1->setDigitCount(5);
        win_1->setSegmentStyle(QLCDNumber::Flat);

        gridLayout->addWidget(win_1, 0, 3, 1, 1);

        layoutWidget1 = new QWidget(centralWidget);
        layoutWidget1->setObjectName(QStringLiteral("layoutWidget1"));
        layoutWidget1->setGeometry(QRect(11, 51, 379, 26));
        gridLayout_2 = new QGridLayout(layoutWidget1);
        gridLayout_2->setSpacing(6);
        gridLayout_2->setContentsMargins(11, 11, 11, 11);
        gridLayout_2->setObjectName(QStringLiteral("gridLayout_2"));
        gridLayout_2->setHorizontalSpacing(3);
        gridLayout_2->setContentsMargins(0, 0, 0, 0);
        select_range_2 = new QPushButton(layoutWidget1);
        select_range_2->setObjectName(QStringLiteral("select_range_2"));
        select_range_2->setIcon(icon);
        select_range_2->setIconSize(QSize(16, 16));

        gridLayout_2->addWidget(select_range_2, 0, 0, 1, 1);

        button_clear_2 = new QPushButton(layoutWidget1);
        button_clear_2->setObjectName(QStringLiteral("button_clear_2"));
        button_clear_2->setIcon(icon1);
        button_clear_2->setIconSize(QSize(16, 16));

        gridLayout_2->addWidget(button_clear_2, 0, 1, 1, 1);

        range_2 = new QLineEdit(layoutWidget1);
        range_2->setObjectName(QStringLiteral("range_2"));
        range_2->setFont(font);
        range_2->setMaxLength(3700);

        gridLayout_2->addWidget(range_2, 0, 2, 1, 1);

        win_2 = new QLCDNumber(layoutWidget1);
        win_2->setObjectName(QStringLiteral("win_2"));
        win_2->setFont(font1);
        win_2->setStyleSheet(QStringLiteral("color: black;"));
        win_2->setFrameShape(QFrame::StyledPanel);
        win_2->setSmallDecimalPoint(true);
        win_2->setDigitCount(5);
        win_2->setSegmentStyle(QLCDNumber::Flat);

        gridLayout_2->addWidget(win_2, 0, 3, 1, 1);

        layoutWidget2 = new QWidget(centralWidget);
        layoutWidget2->setObjectName(QStringLiteral("layoutWidget2"));
        layoutWidget2->setGeometry(QRect(11, 77, 379, 26));
        gridLayout_3 = new QGridLayout(layoutWidget2);
        gridLayout_3->setSpacing(6);
        gridLayout_3->setContentsMargins(11, 11, 11, 11);
        gridLayout_3->setObjectName(QStringLiteral("gridLayout_3"));
        gridLayout_3->setHorizontalSpacing(3);
        gridLayout_3->setContentsMargins(0, 0, 0, 0);
        select_range_3 = new QPushButton(layoutWidget2);
        select_range_3->setObjectName(QStringLiteral("select_range_3"));
        select_range_3->setIcon(icon);
        select_range_3->setIconSize(QSize(16, 16));

        gridLayout_3->addWidget(select_range_3, 0, 0, 1, 1);

        button_clear_3 = new QPushButton(layoutWidget2);
        button_clear_3->setObjectName(QStringLiteral("button_clear_3"));
        button_clear_3->setIcon(icon1);
        button_clear_3->setIconSize(QSize(16, 16));

        gridLayout_3->addWidget(button_clear_3, 0, 1, 1, 1);

        range_3 = new QLineEdit(layoutWidget2);
        range_3->setObjectName(QStringLiteral("range_3"));
        range_3->setFont(font);
        range_3->setMaxLength(3700);

        gridLayout_3->addWidget(range_3, 0, 2, 1, 1);

        win_3 = new QLCDNumber(layoutWidget2);
        win_3->setObjectName(QStringLiteral("win_3"));
        win_3->setFont(font1);
        win_3->setStyleSheet(QStringLiteral("color: black;"));
        win_3->setFrameShape(QFrame::StyledPanel);
        win_3->setSmallDecimalPoint(true);
        win_3->setDigitCount(5);
        win_3->setSegmentStyle(QLCDNumber::Flat);

        gridLayout_3->addWidget(win_3, 0, 3, 1, 1);

        layoutWidget3 = new QWidget(centralWidget);
        layoutWidget3->setObjectName(QStringLiteral("layoutWidget3"));
        layoutWidget3->setGeometry(QRect(11, 103, 379, 26));
        gridLayout_4 = new QGridLayout(layoutWidget3);
        gridLayout_4->setSpacing(6);
        gridLayout_4->setContentsMargins(11, 11, 11, 11);
        gridLayout_4->setObjectName(QStringLiteral("gridLayout_4"));
        gridLayout_4->setHorizontalSpacing(3);
        gridLayout_4->setContentsMargins(0, 0, 0, 0);
        select_range_4 = new QPushButton(layoutWidget3);
        select_range_4->setObjectName(QStringLiteral("select_range_4"));
        select_range_4->setIcon(icon);
        select_range_4->setIconSize(QSize(16, 16));

        gridLayout_4->addWidget(select_range_4, 0, 0, 1, 1);

        button_clear_4 = new QPushButton(layoutWidget3);
        button_clear_4->setObjectName(QStringLiteral("button_clear_4"));
        button_clear_4->setIcon(icon1);
        button_clear_4->setIconSize(QSize(16, 16));

        gridLayout_4->addWidget(button_clear_4, 0, 1, 1, 1);

        range_4 = new QLineEdit(layoutWidget3);
        range_4->setObjectName(QStringLiteral("range_4"));
        range_4->setFont(font);
        range_4->setMaxLength(3700);

        gridLayout_4->addWidget(range_4, 0, 2, 1, 1);

        win_4 = new QLCDNumber(layoutWidget3);
        win_4->setObjectName(QStringLiteral("win_4"));
        win_4->setFont(font1);
        win_4->setStyleSheet(QStringLiteral("color: black;"));
        win_4->setFrameShape(QFrame::StyledPanel);
        win_4->setSmallDecimalPoint(true);
        win_4->setDigitCount(5);
        win_4->setSegmentStyle(QLCDNumber::Flat);

        gridLayout_4->addWidget(win_4, 0, 3, 1, 1);

        layoutWidget4 = new QWidget(centralWidget);
        layoutWidget4->setObjectName(QStringLiteral("layoutWidget4"));
        layoutWidget4->setGeometry(QRect(11, 129, 379, 26));
        gridLayout_5 = new QGridLayout(layoutWidget4);
        gridLayout_5->setSpacing(6);
        gridLayout_5->setContentsMargins(11, 11, 11, 11);
        gridLayout_5->setObjectName(QStringLiteral("gridLayout_5"));
        gridLayout_5->setHorizontalSpacing(3);
        gridLayout_5->setContentsMargins(0, 0, 0, 0);
        select_range_5 = new QPushButton(layoutWidget4);
        select_range_5->setObjectName(QStringLiteral("select_range_5"));
        select_range_5->setIcon(icon);
        select_range_5->setIconSize(QSize(16, 16));

        gridLayout_5->addWidget(select_range_5, 0, 0, 1, 1);

        button_clear_5 = new QPushButton(layoutWidget4);
        button_clear_5->setObjectName(QStringLiteral("button_clear_5"));
        button_clear_5->setIcon(icon1);
        button_clear_5->setIconSize(QSize(16, 16));

        gridLayout_5->addWidget(button_clear_5, 0, 1, 1, 1);

        range_5 = new QLineEdit(layoutWidget4);
        range_5->setObjectName(QStringLiteral("range_5"));
        range_5->setFont(font);
        range_5->setMaxLength(3700);

        gridLayout_5->addWidget(range_5, 0, 2, 1, 1);

        win_5 = new QLCDNumber(layoutWidget4);
        win_5->setObjectName(QStringLiteral("win_5"));
        win_5->setFont(font1);
        win_5->setStyleSheet(QStringLiteral("color: black;"));
        win_5->setFrameShape(QFrame::StyledPanel);
        win_5->setSmallDecimalPoint(true);
        win_5->setDigitCount(5);
        win_5->setSegmentStyle(QLCDNumber::Flat);

        gridLayout_5->addWidget(win_5, 0, 3, 1, 1);

        layoutWidget5 = new QWidget(centralWidget);
        layoutWidget5->setObjectName(QStringLiteral("layoutWidget5"));
        layoutWidget5->setGeometry(QRect(11, 155, 379, 26));
        gridLayout_6 = new QGridLayout(layoutWidget5);
        gridLayout_6->setSpacing(6);
        gridLayout_6->setContentsMargins(11, 11, 11, 11);
        gridLayout_6->setObjectName(QStringLiteral("gridLayout_6"));
        gridLayout_6->setHorizontalSpacing(3);
        gridLayout_6->setContentsMargins(0, 0, 0, 0);
        range_6 = new QLineEdit(layoutWidget5);
        range_6->setObjectName(QStringLiteral("range_6"));
        range_6->setFont(font);
        range_6->setMaxLength(3700);

        gridLayout_6->addWidget(range_6, 0, 2, 1, 1);

        button_clear_6 = new QPushButton(layoutWidget5);
        button_clear_6->setObjectName(QStringLiteral("button_clear_6"));
        button_clear_6->setIcon(icon1);
        button_clear_6->setIconSize(QSize(16, 16));

        gridLayout_6->addWidget(button_clear_6, 0, 1, 1, 1);

        select_range_6 = new QPushButton(layoutWidget5);
        select_range_6->setObjectName(QStringLiteral("select_range_6"));
        select_range_6->setIcon(icon);
        select_range_6->setIconSize(QSize(16, 16));

        gridLayout_6->addWidget(select_range_6, 0, 0, 1, 1);

        win_6 = new QLCDNumber(layoutWidget5);
        win_6->setObjectName(QStringLiteral("win_6"));
        QFont font2;
        font2.setPointSize(9);
        font2.setKerning(true);
        win_6->setFont(font2);
        win_6->setStyleSheet(QStringLiteral("color: black;"));
        win_6->setFrameShape(QFrame::StyledPanel);
        win_6->setFrameShadow(QFrame::Raised);
        win_6->setSmallDecimalPoint(true);
        win_6->setDigitCount(5);
        win_6->setSegmentStyle(QLCDNumber::Flat);

        gridLayout_6->addWidget(win_6, 0, 3, 1, 1);

        card_3a = new QPushButton(centralWidget);
        card_3a->setObjectName(QStringLiteral("card_3a"));
        card_3a->setGeometry(QRect(131, 232, 29, 20));
        card_3a->setFont(font);
        card_3a->setCheckable(true);
        card_29 = new QPushButton(centralWidget);
        card_29->setObjectName(QStringLiteral("card_29"));
        card_29->setGeometry(QRect(160, 272, 29, 20));
        card_29->setFont(font);
        card_29->setCheckable(true);
        card_35 = new QPushButton(centralWidget);
        card_35->setObjectName(QStringLiteral("card_35"));
        card_35->setGeometry(QRect(277, 232, 29, 20));
        card_35->setFont(font);
        card_35->setCheckable(true);
        card_0d = new QPushButton(centralWidget);
        card_0d->setObjectName(QStringLiteral("card_0d"));
        card_0d->setGeometry(QRect(44, 252, 29, 20));
        card_0d->setFont(font);
        card_0d->setCheckable(true);
        card_3b = new QPushButton(centralWidget);
        card_3b->setObjectName(QStringLiteral("card_3b"));
        card_3b->setGeometry(QRect(102, 232, 29, 20));
        card_3b->setFont(font);
        card_3b->setCheckable(true);
        card_12 = new QPushButton(centralWidget);
        card_12->setObjectName(QStringLiteral("card_12"));
        card_12->setGeometry(QRect(364, 292, 29, 20));
        card_12->setFont(font);
        card_12->setCheckable(true);
        card_04 = new QPushButton(centralWidget);
        card_04->setObjectName(QStringLiteral("card_04"));
        card_04->setGeometry(QRect(306, 252, 29, 20));
        card_04->setFont(font);
        card_04->setCheckable(true);
        card_03 = new QPushButton(centralWidget);
        card_03->setObjectName(QStringLiteral("card_03"));
        card_03->setGeometry(QRect(335, 252, 29, 20));
        card_03->setFont(font);
        card_03->setCheckable(true);
        card_0c = new QPushButton(centralWidget);
        card_0c->setObjectName(QStringLiteral("card_0c"));
        card_0c->setGeometry(QRect(73, 252, 29, 20));
        card_0c->setFont(font);
        card_0c->setCheckable(true);
        card_33 = new QPushButton(centralWidget);
        card_33->setObjectName(QStringLiteral("card_33"));
        card_33->setGeometry(QRect(335, 232, 29, 20));
        card_33->setFont(font);
        card_33->setCheckable(true);
        card_37 = new QPushButton(centralWidget);
        card_37->setObjectName(QStringLiteral("card_37"));
        card_37->setGeometry(QRect(219, 232, 29, 20));
        card_37->setFont(font);
        card_37->setCheckable(true);
        card_26 = new QPushButton(centralWidget);
        card_26->setObjectName(QStringLiteral("card_26"));
        card_26->setGeometry(QRect(248, 272, 29, 20));
        card_26->setFont(font);
        card_26->setCheckable(true);
        card_0a = new QPushButton(centralWidget);
        card_0a->setObjectName(QStringLiteral("card_0a"));
        card_0a->setGeometry(QRect(131, 252, 29, 20));
        card_0a->setFont(font);
        card_0a->setCheckable(true);
        card_2e = new QPushButton(centralWidget);
        card_2e->setObjectName(QStringLiteral("card_2e"));
        card_2e->setGeometry(QRect(14, 272, 30, 20));
        card_2e->setFont(font);
        card_2e->setCheckable(true);
        card_1d = new QPushButton(centralWidget);
        card_1d->setObjectName(QStringLiteral("card_1d"));
        card_1d->setGeometry(QRect(44, 292, 29, 20));
        card_1d->setFont(font);
        card_1d->setCheckable(true);
        card_0e = new QPushButton(centralWidget);
        card_0e->setObjectName(QStringLiteral("card_0e"));
        card_0e->setGeometry(QRect(14, 252, 30, 20));
        card_0e->setFont(font);
        card_0e->setCheckable(true);
        card_36 = new QPushButton(centralWidget);
        card_36->setObjectName(QStringLiteral("card_36"));
        card_36->setGeometry(QRect(248, 232, 29, 20));
        card_36->setFont(font);
        card_36->setCheckable(true);
        card_3e = new QPushButton(centralWidget);
        card_3e->setObjectName(QStringLiteral("card_3e"));
        card_3e->setGeometry(QRect(14, 232, 30, 20));
        card_3e->setFont(font);
        card_3e->setCheckable(true);
        card_2a = new QPushButton(centralWidget);
        card_2a->setObjectName(QStringLiteral("card_2a"));
        card_2a->setGeometry(QRect(131, 272, 29, 20));
        card_2a->setFont(font);
        card_2a->setCheckable(true);
        card_24 = new QPushButton(centralWidget);
        card_24->setObjectName(QStringLiteral("card_24"));
        card_24->setGeometry(QRect(306, 272, 29, 20));
        card_24->setFont(font);
        card_24->setCheckable(true);
        card_3d = new QPushButton(centralWidget);
        card_3d->setObjectName(QStringLiteral("card_3d"));
        card_3d->setGeometry(QRect(44, 232, 29, 20));
        card_3d->setFont(font);
        card_3d->setCheckable(true);
        card_38 = new QPushButton(centralWidget);
        card_38->setObjectName(QStringLiteral("card_38"));
        card_38->setGeometry(QRect(189, 232, 30, 20));
        card_38->setFont(font);
        card_38->setCheckable(true);
        card_1c = new QPushButton(centralWidget);
        card_1c->setObjectName(QStringLiteral("card_1c"));
        card_1c->setGeometry(QRect(73, 292, 29, 20));
        card_1c->setFont(font);
        card_1c->setCheckable(true);
        card_0b = new QPushButton(centralWidget);
        card_0b->setObjectName(QStringLiteral("card_0b"));
        card_0b->setGeometry(QRect(102, 252, 29, 20));
        card_0b->setFont(font);
        card_0b->setCheckable(true);
        card_14 = new QPushButton(centralWidget);
        card_14->setObjectName(QStringLiteral("card_14"));
        card_14->setGeometry(QRect(306, 292, 29, 20));
        card_14->setFont(font);
        card_14->setCheckable(true);
        card_19 = new QPushButton(centralWidget);
        card_19->setObjectName(QStringLiteral("card_19"));
        card_19->setGeometry(QRect(160, 292, 29, 20));
        card_19->setFont(font);
        card_19->setCheckable(true);
        card_17 = new QPushButton(centralWidget);
        card_17->setObjectName(QStringLiteral("card_17"));
        card_17->setGeometry(QRect(219, 292, 29, 20));
        card_17->setFont(font);
        card_17->setCheckable(true);
        card_09 = new QPushButton(centralWidget);
        card_09->setObjectName(QStringLiteral("card_09"));
        card_09->setGeometry(QRect(160, 252, 29, 20));
        card_09->setFont(font);
        card_09->setCheckable(true);
        card_13 = new QPushButton(centralWidget);
        card_13->setObjectName(QStringLiteral("card_13"));
        card_13->setGeometry(QRect(335, 292, 29, 20));
        card_13->setFont(font);
        card_13->setCheckable(true);
        button_calculate = new QPushButton(centralWidget);
        button_calculate->setObjectName(QStringLiteral("button_calculate"));
        button_calculate->setGeometry(QRect(310, 200, 80, 22));
        QFont font3;
        font3.setPointSize(8);
        button_calculate->setFont(font3);
        button_calculate->setCheckable(false);
        card_1b = new QPushButton(centralWidget);
        card_1b->setObjectName(QStringLiteral("card_1b"));
        card_1b->setGeometry(QRect(102, 292, 29, 20));
        card_1b->setFont(font);
        card_1b->setCheckable(true);
        card_34 = new QPushButton(centralWidget);
        card_34->setObjectName(QStringLiteral("card_34"));
        card_34->setGeometry(QRect(306, 232, 29, 20));
        card_34->setFont(font);
        card_34->setCheckable(true);
        card_23 = new QPushButton(centralWidget);
        card_23->setObjectName(QStringLiteral("card_23"));
        card_23->setGeometry(QRect(335, 272, 29, 20));
        card_23->setFont(font);
        card_23->setCheckable(true);
        card_02 = new QPushButton(centralWidget);
        card_02->setObjectName(QStringLiteral("card_02"));
        card_02->setGeometry(QRect(364, 252, 29, 20));
        card_02->setFont(font);
        card_02->setCheckable(true);
        card_18 = new QPushButton(centralWidget);
        card_18->setObjectName(QStringLiteral("card_18"));
        card_18->setGeometry(QRect(189, 292, 30, 20));
        card_18->setFont(font);
        card_18->setCheckable(true);
        card_08 = new QPushButton(centralWidget);
        card_08->setObjectName(QStringLiteral("card_08"));
        card_08->setGeometry(QRect(189, 252, 30, 20));
        card_08->setFont(font);
        card_08->setCheckable(true);
        card_06 = new QPushButton(centralWidget);
        card_06->setObjectName(QStringLiteral("card_06"));
        card_06->setGeometry(QRect(248, 252, 29, 20));
        card_06->setFont(font);
        card_06->setCheckable(true);
        card_3c = new QPushButton(centralWidget);
        card_3c->setObjectName(QStringLiteral("card_3c"));
        card_3c->setGeometry(QRect(73, 232, 29, 20));
        card_3c->setFont(font);
        card_3c->setCheckable(true);
        card_07 = new QPushButton(centralWidget);
        card_07->setObjectName(QStringLiteral("card_07"));
        card_07->setGeometry(QRect(219, 252, 29, 20));
        card_07->setFont(font);
        card_07->setCheckable(true);
        card_28 = new QPushButton(centralWidget);
        card_28->setObjectName(QStringLiteral("card_28"));
        card_28->setGeometry(QRect(189, 272, 30, 20));
        card_28->setFont(font);
        card_28->setCheckable(true);
        card_1e = new QPushButton(centralWidget);
        card_1e->setObjectName(QStringLiteral("card_1e"));
        card_1e->setGeometry(QRect(14, 292, 30, 20));
        card_1e->setFont(font);
        card_1e->setCheckable(true);
        card_25 = new QPushButton(centralWidget);
        card_25->setObjectName(QStringLiteral("card_25"));
        card_25->setGeometry(QRect(277, 272, 29, 20));
        card_25->setFont(font);
        card_25->setCheckable(true);
        card_22 = new QPushButton(centralWidget);
        card_22->setObjectName(QStringLiteral("card_22"));
        card_22->setGeometry(QRect(364, 272, 29, 20));
        card_22->setFont(font);
        card_22->setCheckable(true);
        card_2c = new QPushButton(centralWidget);
        card_2c->setObjectName(QStringLiteral("card_2c"));
        card_2c->setGeometry(QRect(73, 272, 29, 20));
        card_2c->setFont(font);
        card_2c->setCheckable(true);
        card_16 = new QPushButton(centralWidget);
        card_16->setObjectName(QStringLiteral("card_16"));
        card_16->setGeometry(QRect(248, 292, 29, 20));
        card_16->setFont(font);
        card_16->setCheckable(true);
        card_2b = new QPushButton(centralWidget);
        card_2b->setObjectName(QStringLiteral("card_2b"));
        card_2b->setGeometry(QRect(102, 272, 29, 20));
        card_2b->setFont(font);
        card_2b->setCheckable(true);
        card_32 = new QPushButton(centralWidget);
        card_32->setObjectName(QStringLiteral("card_32"));
        card_32->setGeometry(QRect(364, 232, 29, 20));
        card_32->setFont(font);
        card_32->setCheckable(true);
        card_05 = new QPushButton(centralWidget);
        card_05->setObjectName(QStringLiteral("card_05"));
        card_05->setGeometry(QRect(277, 252, 29, 20));
        card_05->setFont(font);
        card_05->setCheckable(true);
        card_2d = new QPushButton(centralWidget);
        card_2d->setObjectName(QStringLiteral("card_2d"));
        card_2d->setGeometry(QRect(44, 272, 29, 20));
        card_2d->setFont(font);
        card_2d->setCheckable(true);
        card_15 = new QPushButton(centralWidget);
        card_15->setObjectName(QStringLiteral("card_15"));
        card_15->setGeometry(QRect(277, 292, 29, 20));
        card_15->setFont(font);
        card_15->setCheckable(true);
        card_27 = new QPushButton(centralWidget);
        card_27->setObjectName(QStringLiteral("card_27"));
        card_27->setGeometry(QRect(219, 272, 29, 20));
        card_27->setFont(font);
        card_27->setCheckable(true);
        card_1a = new QPushButton(centralWidget);
        card_1a->setObjectName(QStringLiteral("card_1a"));
        card_1a->setGeometry(QRect(131, 292, 29, 20));
        card_1a->setFont(font);
        card_1a->setCheckable(true);
        button_clear_0 = new QPushButton(centralWidget);
        button_clear_0->setObjectName(QStringLiteral("button_clear_0"));
        button_clear_0->setGeometry(QRect(14, 208, 28, 24));
        button_clear_0->setIcon(icon1);
        button_clear_0->setIconSize(QSize(16, 16));
        card_39 = new QPushButton(centralWidget);
        card_39->setObjectName(QStringLiteral("card_39"));
        card_39->setGeometry(QRect(160, 232, 29, 20));
        card_39->setFont(font);
        card_39->setCheckable(true);
        board_0 = new QPushButton(centralWidget);
        board_0->setObjectName(QStringLiteral("board_0"));
        board_0->setGeometry(QRect(44, 210, 29, 20));
        QPalette palette;
        QBrush brush(QColor(0, 0, 0, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush1(QColor(239, 235, 231, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Button, brush1);
        QBrush brush2(QColor(255, 255, 255, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Light, brush2);
        QBrush brush3(QColor(247, 245, 243, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        QBrush brush4(QColor(119, 117, 115, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Dark, brush4);
        QBrush brush5(QColor(159, 157, 154, 255));
        brush5.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Active, QPalette::Text, brush);
        palette.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Active, QPalette::AlternateBase, brush3);
        QBrush brush6(QColor(255, 255, 220, 255));
        brush6.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::ToolTipBase, brush6);
        palette.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush3);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush6);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        board_0->setPalette(palette);
        board_0->setFont(font);
        board_0->setCheckable(false);
        board_1 = new QPushButton(centralWidget);
        board_1->setObjectName(QStringLiteral("board_1"));
        board_1->setGeometry(QRect(73, 210, 29, 20));
        QPalette palette1;
        palette1.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette1.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette1.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette1.setBrush(QPalette::Active, QPalette::Dark, brush4);
        palette1.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette1.setBrush(QPalette::Active, QPalette::Text, brush);
        palette1.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette1.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette1.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette1.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette1.setBrush(QPalette::Active, QPalette::AlternateBase, brush3);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipBase, brush6);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette1.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette1.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette1.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush3);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette1.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette1.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette1.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette1.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette1.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette1.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette1.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette1.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush6);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        board_1->setPalette(palette1);
        board_1->setFont(font);
        board_1->setCheckable(false);
        board_2 = new QPushButton(centralWidget);
        board_2->setObjectName(QStringLiteral("board_2"));
        board_2->setGeometry(QRect(102, 210, 29, 20));
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette2.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette2.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette2.setBrush(QPalette::Active, QPalette::Dark, brush4);
        palette2.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette2.setBrush(QPalette::Active, QPalette::Text, brush);
        palette2.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette2.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette2.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette2.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette2.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette2.setBrush(QPalette::Active, QPalette::AlternateBase, brush3);
        palette2.setBrush(QPalette::Active, QPalette::ToolTipBase, brush6);
        palette2.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette2.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette2.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette2.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette2.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette2.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette2.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette2.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette2.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush3);
        palette2.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette2.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette2.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette2.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette2.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette2.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette2.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette2.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette2.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        board_2->setPalette(palette2);
        board_2->setFont(font);
        board_2->setCheckable(false);
        board_3 = new QPushButton(centralWidget);
        board_3->setObjectName(QStringLiteral("board_3"));
        board_3->setGeometry(QRect(131, 210, 29, 20));
        QPalette palette3;
        palette3.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette3.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette3.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette3.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette3.setBrush(QPalette::Active, QPalette::Dark, brush4);
        palette3.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette3.setBrush(QPalette::Active, QPalette::Text, brush);
        palette3.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette3.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette3.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette3.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette3.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette3.setBrush(QPalette::Active, QPalette::AlternateBase, brush3);
        palette3.setBrush(QPalette::Active, QPalette::ToolTipBase, brush6);
        palette3.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette3.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette3.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette3.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette3.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette3.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette3.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush3);
        palette3.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush6);
        palette3.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette3.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette3.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette3.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette3.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette3.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette3.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette3.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette3.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush6);
        palette3.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        board_3->setPalette(palette3);
        board_3->setFont(font);
        board_3->setCheckable(false);
        board_4 = new QPushButton(centralWidget);
        board_4->setObjectName(QStringLiteral("board_4"));
        board_4->setGeometry(QRect(160, 210, 29, 20));
        QPalette palette4;
        palette4.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette4.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette4.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette4.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette4.setBrush(QPalette::Active, QPalette::Dark, brush4);
        palette4.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette4.setBrush(QPalette::Active, QPalette::Text, brush);
        palette4.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette4.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette4.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette4.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette4.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette4.setBrush(QPalette::Active, QPalette::AlternateBase, brush3);
        palette4.setBrush(QPalette::Active, QPalette::ToolTipBase, brush6);
        palette4.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette4.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette4.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette4.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette4.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette4.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette4.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette4.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette4.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush3);
        palette4.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush6);
        palette4.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette4.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette4.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette4.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette4.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette4.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette4.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette4.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette4.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush6);
        palette4.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        board_4->setPalette(palette4);
        board_4->setFont(font);
        board_4->setCheckable(false);
        button_clear_all = new QPushButton(centralWidget);
        button_clear_all->setObjectName(QStringLiteral("button_clear_all"));
        button_clear_all->setGeometry(QRect(220, 200, 80, 22));
        button_clear_all->setFont(font3);
        button_clear_all->setCheckable(false);
        MainWindow->setCentralWidget(centralWidget);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        MainWindow->setStatusBar(statusBar);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 406, 20));
        MainWindow->setMenuBar(menuBar);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "EQMain", Q_NULLPTR));
        label_4->setText(QApplication::translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Sans Serif'; font-size:7pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;vertical-align:bottom\">Board</p></body></html>", Q_NULLPTR));
        label_2->setText(QApplication::translate("MainWindow", "<html><head/><body><p align=\"center\">Win</p></body></html>", Q_NULLPTR));
        label->setText(QApplication::translate("MainWindow", "<html><head/><body><p align=\"center\">Hand range</p></body></html>", Q_NULLPTR));
        select_range_1->setText(QString());
        button_clear_1->setText(QString());
        range_1->setText(QString());
        select_range_2->setText(QString());
        button_clear_2->setText(QString());
        range_2->setText(QString());
        select_range_3->setText(QString());
        button_clear_3->setText(QString());
        range_3->setText(QString());
        select_range_4->setText(QString());
        button_clear_4->setText(QString());
        range_4->setText(QString());
        select_range_5->setText(QString());
        button_clear_5->setText(QString());
        range_5->setText(QString());
        range_6->setText(QString());
        button_clear_6->setText(QString());
        select_range_6->setText(QString());
        card_3a->setText(QApplication::translate("MainWindow", "Tc", Q_NULLPTR));
        card_29->setText(QApplication::translate("MainWindow", "9s", Q_NULLPTR));
        card_35->setText(QApplication::translate("MainWindow", "5c", Q_NULLPTR));
        card_0d->setText(QApplication::translate("MainWindow", "Kh", Q_NULLPTR));
        card_3b->setText(QApplication::translate("MainWindow", "Jc", Q_NULLPTR));
        card_12->setText(QApplication::translate("MainWindow", "2d", Q_NULLPTR));
        card_04->setText(QApplication::translate("MainWindow", "4h", Q_NULLPTR));
        card_03->setText(QApplication::translate("MainWindow", "3h", Q_NULLPTR));
        card_0c->setText(QApplication::translate("MainWindow", "Qh", Q_NULLPTR));
        card_33->setText(QApplication::translate("MainWindow", "3c", Q_NULLPTR));
        card_37->setText(QApplication::translate("MainWindow", "7c", Q_NULLPTR));
        card_26->setText(QApplication::translate("MainWindow", "6s", Q_NULLPTR));
        card_0a->setText(QApplication::translate("MainWindow", "Th", Q_NULLPTR));
        card_2e->setText(QApplication::translate("MainWindow", "As", Q_NULLPTR));
        card_1d->setText(QApplication::translate("MainWindow", "Kd", Q_NULLPTR));
        card_0e->setText(QApplication::translate("MainWindow", "Ah", Q_NULLPTR));
        card_36->setText(QApplication::translate("MainWindow", "6c", Q_NULLPTR));
        card_3e->setText(QApplication::translate("MainWindow", "Ac", Q_NULLPTR));
        card_2a->setText(QApplication::translate("MainWindow", "Ts", Q_NULLPTR));
        card_24->setText(QApplication::translate("MainWindow", "4s", Q_NULLPTR));
        card_3d->setText(QApplication::translate("MainWindow", "Kc", Q_NULLPTR));
        card_38->setText(QApplication::translate("MainWindow", "8c", Q_NULLPTR));
        card_1c->setText(QApplication::translate("MainWindow", "Qd", Q_NULLPTR));
        card_0b->setText(QApplication::translate("MainWindow", "Jh", Q_NULLPTR));
        card_14->setText(QApplication::translate("MainWindow", "4d", Q_NULLPTR));
        card_19->setText(QApplication::translate("MainWindow", "9d", Q_NULLPTR));
        card_17->setText(QApplication::translate("MainWindow", "7d", Q_NULLPTR));
        card_09->setText(QApplication::translate("MainWindow", "9h", Q_NULLPTR));
        card_13->setText(QApplication::translate("MainWindow", "3d", Q_NULLPTR));
        button_calculate->setText(QApplication::translate("MainWindow", "Calculate EQ", Q_NULLPTR));
        card_1b->setText(QApplication::translate("MainWindow", "Jd", Q_NULLPTR));
        card_34->setText(QApplication::translate("MainWindow", "4c", Q_NULLPTR));
        card_23->setText(QApplication::translate("MainWindow", "3s", Q_NULLPTR));
        card_02->setText(QApplication::translate("MainWindow", "2n", Q_NULLPTR));
        card_18->setText(QApplication::translate("MainWindow", "8d", Q_NULLPTR));
        card_08->setText(QApplication::translate("MainWindow", "8h", Q_NULLPTR));
        card_06->setText(QApplication::translate("MainWindow", "6h", Q_NULLPTR));
        card_3c->setText(QApplication::translate("MainWindow", "Qc", Q_NULLPTR));
        card_07->setText(QApplication::translate("MainWindow", "7h", Q_NULLPTR));
        card_28->setText(QApplication::translate("MainWindow", "8s", Q_NULLPTR));
        card_1e->setText(QApplication::translate("MainWindow", "Ad", Q_NULLPTR));
        card_25->setText(QApplication::translate("MainWindow", "5s", Q_NULLPTR));
        card_22->setText(QApplication::translate("MainWindow", "2s", Q_NULLPTR));
        card_2c->setText(QApplication::translate("MainWindow", "Qs", Q_NULLPTR));
        card_16->setText(QApplication::translate("MainWindow", "6d", Q_NULLPTR));
        card_2b->setText(QApplication::translate("MainWindow", "Js", Q_NULLPTR));
        card_32->setText(QApplication::translate("MainWindow", "2s", Q_NULLPTR));
        card_05->setText(QApplication::translate("MainWindow", "5h", Q_NULLPTR));
        card_2d->setText(QApplication::translate("MainWindow", "Ks", Q_NULLPTR));
        card_15->setText(QApplication::translate("MainWindow", "5d", Q_NULLPTR));
        card_27->setText(QApplication::translate("MainWindow", "7s", Q_NULLPTR));
        card_1a->setText(QApplication::translate("MainWindow", "Td", Q_NULLPTR));
        button_clear_0->setText(QString());
        card_39->setText(QApplication::translate("MainWindow", "9c", Q_NULLPTR));
        board_0->setText(QString());
        board_1->setText(QString());
        board_2->setText(QString());
        board_3->setText(QString());
        board_4->setText(QString());
        button_clear_all->setText(QApplication::translate("MainWindow", "Clear All", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
