/********************************************************************************
** Form generated from reading UI file 'winselectrange.ui'
**
** Created by: Qt User Interface Compiler version 5.9.5
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_WINSELECTRANGE_H
#define UI_WINSELECTRANGE_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QDialog>
#include <QtWidgets/QGridLayout>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_WinSelectRange
{
public:
    QPushButton *button_ok;
    QPushButton *button_clear;
    QPushButton *combo_AA;
    QPushButton *combo_AKs;
    QPushButton *combo_AQs;
    QPushButton *combo_AJs;
    QPushButton *combo_ATs;
    QPushButton *combo_A9s;
    QPushButton *combo_A8s;
    QPushButton *combo_A7s;
    QPushButton *combo_A6s;
    QPushButton *combo_A5s;
    QPushButton *combo_A4s;
    QPushButton *combo_A3s;
    QPushButton *combo_A2s;
    QPushButton *combo_AKo;
    QPushButton *combo_KK;
    QPushButton *combo_KQs;
    QPushButton *combo_KJs;
    QPushButton *combo_KTs;
    QPushButton *combo_K9s;
    QPushButton *combo_K8s;
    QPushButton *combo_K7s;
    QPushButton *combo_K6s;
    QPushButton *combo_K5s;
    QPushButton *combo_K4s;
    QPushButton *combo_K3s;
    QPushButton *combo_K2s;
    QPushButton *combo_AQo;
    QPushButton *combo_KQo;
    QPushButton *combo_QQ;
    QPushButton *combo_QJs;
    QPushButton *combo_QTs;
    QPushButton *combo_Q9s;
    QPushButton *combo_Q8s;
    QPushButton *combo_Q7s;
    QPushButton *combo_Q6s;
    QPushButton *combo_Q5s;
    QPushButton *combo_Q4s;
    QPushButton *combo_Q3s;
    QPushButton *combo_Q2s;
    QPushButton *combo_AJo;
    QPushButton *combo_KJo;
    QPushButton *combo_QJo;
    QPushButton *combo_JJ;
    QPushButton *combo_JTs;
    QPushButton *combo_J9s;
    QPushButton *combo_J8s;
    QPushButton *combo_J7s;
    QPushButton *combo_J6s;
    QPushButton *combo_J5s;
    QPushButton *combo_J4s;
    QPushButton *combo_J3s;
    QPushButton *combo_J2s;
    QPushButton *combo_ATo;
    QPushButton *combo_KTo;
    QPushButton *combo_QTo;
    QPushButton *combo_JTo;
    QPushButton *combo_TT;
    QPushButton *combo_T9s;
    QPushButton *combo_T8s;
    QPushButton *combo_T7s;
    QPushButton *combo_T6s;
    QPushButton *combo_T5s;
    QPushButton *combo_T4s;
    QPushButton *combo_T3s;
    QPushButton *combo_T2s;
    QPushButton *combo_A9o;
    QPushButton *combo_K9o;
    QPushButton *combo_Q9o;
    QPushButton *combo_J9o;
    QPushButton *combo_T9o;
    QPushButton *combo_99;
    QPushButton *combo_98s;
    QPushButton *combo_97s;
    QPushButton *combo_96s;
    QPushButton *combo_95s;
    QPushButton *combo_94s;
    QPushButton *combo_93s;
    QPushButton *combo_92s;
    QPushButton *combo_A8o;
    QPushButton *combo_K8o;
    QPushButton *combo_Q8o;
    QPushButton *combo_J8o;
    QPushButton *combo_T8o;
    QPushButton *combo_98o;
    QPushButton *combo_88;
    QPushButton *combo_87s;
    QPushButton *combo_86s;
    QPushButton *combo_85s;
    QPushButton *combo_84s;
    QPushButton *combo_83s;
    QPushButton *combo_82s;
    QPushButton *combo_A7o;
    QPushButton *combo_K7o;
    QPushButton *combo_Q7o;
    QPushButton *combo_J7o;
    QPushButton *combo_T7o;
    QPushButton *combo_97o;
    QPushButton *combo_87o;
    QPushButton *combo_77;
    QPushButton *combo_76s;
    QPushButton *combo_75s;
    QPushButton *combo_74s;
    QPushButton *combo_73s;
    QPushButton *combo_72s;
    QPushButton *combo_A6o;
    QPushButton *combo_K6o;
    QPushButton *combo_Q6o;
    QPushButton *combo_J6o;
    QPushButton *combo_T6o;
    QPushButton *combo_96o;
    QPushButton *combo_86o;
    QPushButton *combo_76o;
    QPushButton *combo_66;
    QPushButton *combo_65s;
    QPushButton *combo_64s;
    QPushButton *combo_63s;
    QPushButton *combo_62s;
    QPushButton *combo_A5o;
    QPushButton *combo_K5o;
    QPushButton *combo_Q5o;
    QPushButton *combo_J5o;
    QPushButton *combo_T5o;
    QPushButton *combo_95o;
    QPushButton *combo_85o;
    QPushButton *combo_75o;
    QPushButton *combo_65o;
    QPushButton *combo_55;
    QPushButton *combo_54s;
    QPushButton *combo_53s;
    QPushButton *combo_52s;
    QPushButton *combo_A4o;
    QPushButton *combo_K4o;
    QPushButton *combo_Q4o;
    QPushButton *combo_J4o;
    QPushButton *combo_T4o;
    QPushButton *combo_94o;
    QPushButton *combo_84o;
    QPushButton *combo_74o;
    QPushButton *combo_64o;
    QPushButton *combo_54o;
    QPushButton *combo_44;
    QPushButton *combo_43s;
    QPushButton *combo_42s;
    QPushButton *combo_A3o;
    QPushButton *combo_K3o;
    QPushButton *combo_Q3o;
    QPushButton *combo_J3o;
    QPushButton *combo_T3o;
    QPushButton *combo_93o;
    QPushButton *combo_83o;
    QPushButton *combo_73o;
    QPushButton *combo_63o;
    QPushButton *combo_53o;
    QPushButton *combo_43o;
    QPushButton *combo_33;
    QPushButton *combo_32s;
    QPushButton *combo_A2o;
    QPushButton *combo_K2o;
    QPushButton *combo_Q2o;
    QPushButton *combo_J2o;
    QPushButton *combo_T2o;
    QPushButton *combo_92o;
    QPushButton *combo_82o;
    QPushButton *combo_72o;
    QPushButton *combo_62o;
    QPushButton *combo_52o;
    QPushButton *combo_42o;
    QPushButton *combo_32o;
    QPushButton *combo_22;
    QCheckBox *chk_suit_selector;
    QPushButton *button_cancel;
    QLabel *label_2;
    QPushButton *suit_03;
    QPushButton *suit_20;
    QPushButton *suit_22;
    QPushButton *suit_21;
    QPushButton *suit_30;
    QPushButton *suit_11;
    QPushButton *suit_10;
    QPushButton *suit_12;
    QPushButton *suit_00;
    QPushButton *suit_01;
    QPushButton *suit_32;
    QPushButton *suit_31;
    QPushButton *suit_02;
    QPushButton *suit_13;
    QPushButton *suit_33;
    QPushButton *suit_23;
    QWidget *layoutWidget;
    QGridLayout *gridLayout;
    QLabel *label_vpip;
    QLineEdit *line_vpip;
    QLabel *label_pfr;
    QLineEdit *line_pfr;

    void setupUi(QDialog *WinSelectRange)
    {
        if (WinSelectRange->objectName().isEmpty())
            WinSelectRange->setObjectName(QStringLiteral("WinSelectRange"));
        WinSelectRange->resize(595, 403);
        QSizePolicy sizePolicy(QSizePolicy::Fixed, QSizePolicy::Fixed);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(WinSelectRange->sizePolicy().hasHeightForWidth());
        WinSelectRange->setSizePolicy(sizePolicy);
        button_ok = new QPushButton(WinSelectRange);
        button_ok->setObjectName(QStringLiteral("button_ok"));
        button_ok->setGeometry(QRect(470, 250, 111, 23));
        button_clear = new QPushButton(WinSelectRange);
        button_clear->setObjectName(QStringLiteral("button_clear"));
        button_clear->setGeometry(QRect(470, 308, 111, 23));
        combo_AA = new QPushButton(WinSelectRange);
        combo_AA->setObjectName(QStringLiteral("combo_AA"));
        combo_AA->setGeometry(QRect(13, 44, 34, 22));
        QFont font;
        font.setPointSize(7);
        combo_AA->setFont(font);
        combo_AA->setAutoFillBackground(false);
        combo_AA->setStyleSheet(QStringLiteral(""));
        combo_AA->setCheckable(true);
        combo_AKs = new QPushButton(WinSelectRange);
        combo_AKs->setObjectName(QStringLiteral("combo_AKs"));
        combo_AKs->setGeometry(QRect(48, 44, 34, 22));
        combo_AKs->setFont(font);
        combo_AKs->setStyleSheet(QStringLiteral(""));
        combo_AKs->setCheckable(true);
        combo_AQs = new QPushButton(WinSelectRange);
        combo_AQs->setObjectName(QStringLiteral("combo_AQs"));
        combo_AQs->setGeometry(QRect(83, 44, 33, 22));
        combo_AQs->setFont(font);
        combo_AQs->setStyleSheet(QStringLiteral(""));
        combo_AQs->setCheckable(true);
        combo_AJs = new QPushButton(WinSelectRange);
        combo_AJs->setObjectName(QStringLiteral("combo_AJs"));
        combo_AJs->setGeometry(QRect(117, 44, 34, 22));
        combo_AJs->setFont(font);
        combo_AJs->setStyleSheet(QStringLiteral(""));
        combo_AJs->setCheckable(true);
        combo_ATs = new QPushButton(WinSelectRange);
        combo_ATs->setObjectName(QStringLiteral("combo_ATs"));
        combo_ATs->setGeometry(QRect(152, 44, 34, 22));
        combo_ATs->setFont(font);
        combo_ATs->setStyleSheet(QStringLiteral(""));
        combo_ATs->setCheckable(true);
        combo_A9s = new QPushButton(WinSelectRange);
        combo_A9s->setObjectName(QStringLiteral("combo_A9s"));
        combo_A9s->setGeometry(QRect(187, 44, 33, 22));
        combo_A9s->setFont(font);
        combo_A9s->setStyleSheet(QStringLiteral(""));
        combo_A9s->setCheckable(true);
        combo_A8s = new QPushButton(WinSelectRange);
        combo_A8s->setObjectName(QStringLiteral("combo_A8s"));
        combo_A8s->setGeometry(QRect(221, 44, 34, 22));
        combo_A8s->setFont(font);
        combo_A8s->setStyleSheet(QStringLiteral(""));
        combo_A8s->setCheckable(true);
        combo_A7s = new QPushButton(WinSelectRange);
        combo_A7s->setObjectName(QStringLiteral("combo_A7s"));
        combo_A7s->setGeometry(QRect(256, 44, 33, 22));
        combo_A7s->setFont(font);
        combo_A7s->setStyleSheet(QStringLiteral(""));
        combo_A7s->setCheckable(true);
        combo_A6s = new QPushButton(WinSelectRange);
        combo_A6s->setObjectName(QStringLiteral("combo_A6s"));
        combo_A6s->setGeometry(QRect(290, 44, 34, 22));
        combo_A6s->setFont(font);
        combo_A6s->setStyleSheet(QStringLiteral(""));
        combo_A6s->setCheckable(true);
        combo_A5s = new QPushButton(WinSelectRange);
        combo_A5s->setObjectName(QStringLiteral("combo_A5s"));
        combo_A5s->setGeometry(QRect(325, 44, 34, 22));
        combo_A5s->setFont(font);
        combo_A5s->setStyleSheet(QStringLiteral(""));
        combo_A5s->setCheckable(true);
        combo_A4s = new QPushButton(WinSelectRange);
        combo_A4s->setObjectName(QStringLiteral("combo_A4s"));
        combo_A4s->setGeometry(QRect(360, 44, 33, 22));
        combo_A4s->setFont(font);
        combo_A4s->setStyleSheet(QStringLiteral(""));
        combo_A4s->setCheckable(true);
        combo_A3s = new QPushButton(WinSelectRange);
        combo_A3s->setObjectName(QStringLiteral("combo_A3s"));
        combo_A3s->setGeometry(QRect(394, 44, 34, 22));
        combo_A3s->setFont(font);
        combo_A3s->setStyleSheet(QStringLiteral(""));
        combo_A3s->setCheckable(true);
        combo_A2s = new QPushButton(WinSelectRange);
        combo_A2s->setObjectName(QStringLiteral("combo_A2s"));
        combo_A2s->setGeometry(QRect(429, 44, 33, 22));
        combo_A2s->setFont(font);
        combo_A2s->setStyleSheet(QStringLiteral(""));
        combo_A2s->setCheckable(true);
        combo_AKo = new QPushButton(WinSelectRange);
        combo_AKo->setObjectName(QStringLiteral("combo_AKo"));
        combo_AKo->setGeometry(QRect(13, 66, 34, 22));
        combo_AKo->setFont(font);
        combo_AKo->setStyleSheet(QStringLiteral(""));
        combo_AKo->setCheckable(true);
        combo_KK = new QPushButton(WinSelectRange);
        combo_KK->setObjectName(QStringLiteral("combo_KK"));
        combo_KK->setGeometry(QRect(48, 66, 34, 22));
        combo_KK->setFont(font);
        combo_KK->setAutoFillBackground(false);
        combo_KK->setStyleSheet(QStringLiteral(""));
        combo_KK->setCheckable(true);
        combo_KQs = new QPushButton(WinSelectRange);
        combo_KQs->setObjectName(QStringLiteral("combo_KQs"));
        combo_KQs->setGeometry(QRect(83, 66, 33, 22));
        combo_KQs->setFont(font);
        combo_KQs->setStyleSheet(QStringLiteral(""));
        combo_KQs->setCheckable(true);
        combo_KJs = new QPushButton(WinSelectRange);
        combo_KJs->setObjectName(QStringLiteral("combo_KJs"));
        combo_KJs->setGeometry(QRect(117, 66, 34, 22));
        combo_KJs->setFont(font);
        combo_KJs->setStyleSheet(QStringLiteral(""));
        combo_KJs->setCheckable(true);
        combo_KTs = new QPushButton(WinSelectRange);
        combo_KTs->setObjectName(QStringLiteral("combo_KTs"));
        combo_KTs->setGeometry(QRect(152, 66, 34, 22));
        combo_KTs->setFont(font);
        combo_KTs->setStyleSheet(QStringLiteral(""));
        combo_KTs->setCheckable(true);
        combo_K9s = new QPushButton(WinSelectRange);
        combo_K9s->setObjectName(QStringLiteral("combo_K9s"));
        combo_K9s->setGeometry(QRect(187, 66, 33, 22));
        combo_K9s->setFont(font);
        combo_K9s->setStyleSheet(QStringLiteral(""));
        combo_K9s->setCheckable(true);
        combo_K8s = new QPushButton(WinSelectRange);
        combo_K8s->setObjectName(QStringLiteral("combo_K8s"));
        combo_K8s->setGeometry(QRect(221, 66, 34, 22));
        combo_K8s->setFont(font);
        combo_K8s->setStyleSheet(QStringLiteral(""));
        combo_K8s->setCheckable(true);
        combo_K7s = new QPushButton(WinSelectRange);
        combo_K7s->setObjectName(QStringLiteral("combo_K7s"));
        combo_K7s->setGeometry(QRect(256, 66, 33, 22));
        combo_K7s->setFont(font);
        combo_K7s->setStyleSheet(QStringLiteral(""));
        combo_K7s->setCheckable(true);
        combo_K6s = new QPushButton(WinSelectRange);
        combo_K6s->setObjectName(QStringLiteral("combo_K6s"));
        combo_K6s->setGeometry(QRect(290, 66, 34, 22));
        combo_K6s->setFont(font);
        combo_K6s->setStyleSheet(QStringLiteral(""));
        combo_K6s->setCheckable(true);
        combo_K5s = new QPushButton(WinSelectRange);
        combo_K5s->setObjectName(QStringLiteral("combo_K5s"));
        combo_K5s->setGeometry(QRect(325, 66, 34, 22));
        combo_K5s->setFont(font);
        combo_K5s->setStyleSheet(QStringLiteral(""));
        combo_K5s->setCheckable(true);
        combo_K4s = new QPushButton(WinSelectRange);
        combo_K4s->setObjectName(QStringLiteral("combo_K4s"));
        combo_K4s->setGeometry(QRect(360, 66, 33, 22));
        combo_K4s->setFont(font);
        combo_K4s->setStyleSheet(QStringLiteral(""));
        combo_K4s->setCheckable(true);
        combo_K3s = new QPushButton(WinSelectRange);
        combo_K3s->setObjectName(QStringLiteral("combo_K3s"));
        combo_K3s->setGeometry(QRect(394, 66, 34, 22));
        combo_K3s->setFont(font);
        combo_K3s->setStyleSheet(QStringLiteral(""));
        combo_K3s->setCheckable(true);
        combo_K2s = new QPushButton(WinSelectRange);
        combo_K2s->setObjectName(QStringLiteral("combo_K2s"));
        combo_K2s->setGeometry(QRect(429, 66, 33, 22));
        combo_K2s->setFont(font);
        combo_K2s->setStyleSheet(QStringLiteral(""));
        combo_K2s->setCheckable(true);
        combo_AQo = new QPushButton(WinSelectRange);
        combo_AQo->setObjectName(QStringLiteral("combo_AQo"));
        combo_AQo->setGeometry(QRect(13, 88, 34, 22));
        combo_AQo->setFont(font);
        combo_AQo->setStyleSheet(QStringLiteral(""));
        combo_AQo->setCheckable(true);
        combo_KQo = new QPushButton(WinSelectRange);
        combo_KQo->setObjectName(QStringLiteral("combo_KQo"));
        combo_KQo->setGeometry(QRect(48, 88, 34, 22));
        combo_KQo->setFont(font);
        combo_KQo->setStyleSheet(QStringLiteral(""));
        combo_KQo->setCheckable(true);
        combo_QQ = new QPushButton(WinSelectRange);
        combo_QQ->setObjectName(QStringLiteral("combo_QQ"));
        combo_QQ->setGeometry(QRect(83, 88, 33, 22));
        combo_QQ->setFont(font);
        combo_QQ->setAutoFillBackground(false);
        combo_QQ->setStyleSheet(QStringLiteral(""));
        combo_QQ->setCheckable(true);
        combo_QJs = new QPushButton(WinSelectRange);
        combo_QJs->setObjectName(QStringLiteral("combo_QJs"));
        combo_QJs->setGeometry(QRect(117, 88, 34, 22));
        combo_QJs->setFont(font);
        combo_QJs->setStyleSheet(QStringLiteral(""));
        combo_QJs->setCheckable(true);
        combo_QTs = new QPushButton(WinSelectRange);
        combo_QTs->setObjectName(QStringLiteral("combo_QTs"));
        combo_QTs->setGeometry(QRect(152, 88, 34, 22));
        combo_QTs->setFont(font);
        combo_QTs->setStyleSheet(QStringLiteral(""));
        combo_QTs->setCheckable(true);
        combo_Q9s = new QPushButton(WinSelectRange);
        combo_Q9s->setObjectName(QStringLiteral("combo_Q9s"));
        combo_Q9s->setGeometry(QRect(187, 88, 33, 22));
        combo_Q9s->setFont(font);
        combo_Q9s->setStyleSheet(QStringLiteral(""));
        combo_Q9s->setCheckable(true);
        combo_Q8s = new QPushButton(WinSelectRange);
        combo_Q8s->setObjectName(QStringLiteral("combo_Q8s"));
        combo_Q8s->setGeometry(QRect(221, 88, 34, 22));
        combo_Q8s->setFont(font);
        combo_Q8s->setStyleSheet(QStringLiteral(""));
        combo_Q8s->setCheckable(true);
        combo_Q7s = new QPushButton(WinSelectRange);
        combo_Q7s->setObjectName(QStringLiteral("combo_Q7s"));
        combo_Q7s->setGeometry(QRect(256, 88, 33, 22));
        combo_Q7s->setFont(font);
        combo_Q7s->setStyleSheet(QStringLiteral(""));
        combo_Q7s->setCheckable(true);
        combo_Q6s = new QPushButton(WinSelectRange);
        combo_Q6s->setObjectName(QStringLiteral("combo_Q6s"));
        combo_Q6s->setGeometry(QRect(290, 88, 34, 22));
        combo_Q6s->setFont(font);
        combo_Q6s->setStyleSheet(QStringLiteral(""));
        combo_Q6s->setCheckable(true);
        combo_Q5s = new QPushButton(WinSelectRange);
        combo_Q5s->setObjectName(QStringLiteral("combo_Q5s"));
        combo_Q5s->setGeometry(QRect(325, 88, 34, 22));
        combo_Q5s->setFont(font);
        combo_Q5s->setStyleSheet(QStringLiteral(""));
        combo_Q5s->setCheckable(true);
        combo_Q4s = new QPushButton(WinSelectRange);
        combo_Q4s->setObjectName(QStringLiteral("combo_Q4s"));
        combo_Q4s->setGeometry(QRect(360, 88, 33, 22));
        combo_Q4s->setFont(font);
        combo_Q4s->setStyleSheet(QStringLiteral(""));
        combo_Q4s->setCheckable(true);
        combo_Q3s = new QPushButton(WinSelectRange);
        combo_Q3s->setObjectName(QStringLiteral("combo_Q3s"));
        combo_Q3s->setGeometry(QRect(394, 88, 34, 22));
        combo_Q3s->setFont(font);
        combo_Q3s->setStyleSheet(QStringLiteral(""));
        combo_Q3s->setCheckable(true);
        combo_Q2s = new QPushButton(WinSelectRange);
        combo_Q2s->setObjectName(QStringLiteral("combo_Q2s"));
        combo_Q2s->setGeometry(QRect(429, 88, 33, 22));
        combo_Q2s->setFont(font);
        combo_Q2s->setStyleSheet(QStringLiteral(""));
        combo_Q2s->setCheckable(true);
        combo_AJo = new QPushButton(WinSelectRange);
        combo_AJo->setObjectName(QStringLiteral("combo_AJo"));
        combo_AJo->setGeometry(QRect(13, 110, 34, 22));
        combo_AJo->setFont(font);
        combo_AJo->setStyleSheet(QStringLiteral(""));
        combo_AJo->setCheckable(true);
        combo_KJo = new QPushButton(WinSelectRange);
        combo_KJo->setObjectName(QStringLiteral("combo_KJo"));
        combo_KJo->setGeometry(QRect(48, 110, 34, 22));
        combo_KJo->setFont(font);
        combo_KJo->setStyleSheet(QStringLiteral(""));
        combo_KJo->setCheckable(true);
        combo_QJo = new QPushButton(WinSelectRange);
        combo_QJo->setObjectName(QStringLiteral("combo_QJo"));
        combo_QJo->setGeometry(QRect(83, 110, 33, 22));
        combo_QJo->setFont(font);
        combo_QJo->setStyleSheet(QStringLiteral(""));
        combo_QJo->setCheckable(true);
        combo_JJ = new QPushButton(WinSelectRange);
        combo_JJ->setObjectName(QStringLiteral("combo_JJ"));
        combo_JJ->setGeometry(QRect(117, 110, 34, 22));
        combo_JJ->setFont(font);
        combo_JJ->setAutoFillBackground(false);
        combo_JJ->setStyleSheet(QStringLiteral(""));
        combo_JJ->setCheckable(true);
        combo_JTs = new QPushButton(WinSelectRange);
        combo_JTs->setObjectName(QStringLiteral("combo_JTs"));
        combo_JTs->setGeometry(QRect(152, 110, 34, 22));
        combo_JTs->setFont(font);
        combo_JTs->setStyleSheet(QStringLiteral(""));
        combo_JTs->setCheckable(true);
        combo_J9s = new QPushButton(WinSelectRange);
        combo_J9s->setObjectName(QStringLiteral("combo_J9s"));
        combo_J9s->setGeometry(QRect(187, 110, 33, 22));
        combo_J9s->setFont(font);
        combo_J9s->setStyleSheet(QStringLiteral(""));
        combo_J9s->setCheckable(true);
        combo_J8s = new QPushButton(WinSelectRange);
        combo_J8s->setObjectName(QStringLiteral("combo_J8s"));
        combo_J8s->setGeometry(QRect(221, 110, 34, 22));
        combo_J8s->setFont(font);
        combo_J8s->setStyleSheet(QStringLiteral(""));
        combo_J8s->setCheckable(true);
        combo_J7s = new QPushButton(WinSelectRange);
        combo_J7s->setObjectName(QStringLiteral("combo_J7s"));
        combo_J7s->setGeometry(QRect(256, 110, 33, 22));
        combo_J7s->setFont(font);
        combo_J7s->setStyleSheet(QStringLiteral(""));
        combo_J7s->setCheckable(true);
        combo_J6s = new QPushButton(WinSelectRange);
        combo_J6s->setObjectName(QStringLiteral("combo_J6s"));
        combo_J6s->setGeometry(QRect(290, 110, 34, 22));
        combo_J6s->setFont(font);
        combo_J6s->setStyleSheet(QStringLiteral(""));
        combo_J6s->setCheckable(true);
        combo_J5s = new QPushButton(WinSelectRange);
        combo_J5s->setObjectName(QStringLiteral("combo_J5s"));
        combo_J5s->setGeometry(QRect(325, 110, 34, 22));
        combo_J5s->setFont(font);
        combo_J5s->setStyleSheet(QStringLiteral(""));
        combo_J5s->setCheckable(true);
        combo_J4s = new QPushButton(WinSelectRange);
        combo_J4s->setObjectName(QStringLiteral("combo_J4s"));
        combo_J4s->setGeometry(QRect(360, 110, 33, 22));
        combo_J4s->setFont(font);
        combo_J4s->setStyleSheet(QStringLiteral(""));
        combo_J4s->setCheckable(true);
        combo_J3s = new QPushButton(WinSelectRange);
        combo_J3s->setObjectName(QStringLiteral("combo_J3s"));
        combo_J3s->setGeometry(QRect(394, 110, 34, 22));
        combo_J3s->setFont(font);
        combo_J3s->setStyleSheet(QStringLiteral(""));
        combo_J3s->setCheckable(true);
        combo_J2s = new QPushButton(WinSelectRange);
        combo_J2s->setObjectName(QStringLiteral("combo_J2s"));
        combo_J2s->setGeometry(QRect(429, 110, 33, 22));
        combo_J2s->setFont(font);
        combo_J2s->setStyleSheet(QStringLiteral(""));
        combo_J2s->setCheckable(true);
        combo_ATo = new QPushButton(WinSelectRange);
        combo_ATo->setObjectName(QStringLiteral("combo_ATo"));
        combo_ATo->setGeometry(QRect(13, 132, 34, 22));
        combo_ATo->setFont(font);
        combo_ATo->setStyleSheet(QStringLiteral(""));
        combo_ATo->setCheckable(true);
        combo_KTo = new QPushButton(WinSelectRange);
        combo_KTo->setObjectName(QStringLiteral("combo_KTo"));
        combo_KTo->setGeometry(QRect(48, 132, 34, 22));
        combo_KTo->setFont(font);
        combo_KTo->setStyleSheet(QStringLiteral(""));
        combo_KTo->setCheckable(true);
        combo_QTo = new QPushButton(WinSelectRange);
        combo_QTo->setObjectName(QStringLiteral("combo_QTo"));
        combo_QTo->setGeometry(QRect(83, 132, 33, 22));
        combo_QTo->setFont(font);
        combo_QTo->setStyleSheet(QStringLiteral(""));
        combo_QTo->setCheckable(true);
        combo_JTo = new QPushButton(WinSelectRange);
        combo_JTo->setObjectName(QStringLiteral("combo_JTo"));
        combo_JTo->setGeometry(QRect(117, 132, 34, 22));
        combo_JTo->setFont(font);
        combo_JTo->setStyleSheet(QStringLiteral(""));
        combo_JTo->setCheckable(true);
        combo_TT = new QPushButton(WinSelectRange);
        combo_TT->setObjectName(QStringLiteral("combo_TT"));
        combo_TT->setGeometry(QRect(152, 132, 34, 22));
        combo_TT->setFont(font);
        combo_TT->setAutoFillBackground(false);
        combo_TT->setStyleSheet(QStringLiteral(""));
        combo_TT->setCheckable(true);
        combo_T9s = new QPushButton(WinSelectRange);
        combo_T9s->setObjectName(QStringLiteral("combo_T9s"));
        combo_T9s->setGeometry(QRect(187, 132, 33, 22));
        combo_T9s->setFont(font);
        combo_T9s->setStyleSheet(QStringLiteral(""));
        combo_T9s->setCheckable(true);
        combo_T8s = new QPushButton(WinSelectRange);
        combo_T8s->setObjectName(QStringLiteral("combo_T8s"));
        combo_T8s->setGeometry(QRect(221, 132, 34, 22));
        combo_T8s->setFont(font);
        combo_T8s->setStyleSheet(QStringLiteral(""));
        combo_T8s->setCheckable(true);
        combo_T7s = new QPushButton(WinSelectRange);
        combo_T7s->setObjectName(QStringLiteral("combo_T7s"));
        combo_T7s->setGeometry(QRect(256, 132, 33, 22));
        combo_T7s->setFont(font);
        combo_T7s->setStyleSheet(QStringLiteral(""));
        combo_T7s->setCheckable(true);
        combo_T6s = new QPushButton(WinSelectRange);
        combo_T6s->setObjectName(QStringLiteral("combo_T6s"));
        combo_T6s->setGeometry(QRect(290, 132, 34, 22));
        combo_T6s->setFont(font);
        combo_T6s->setStyleSheet(QStringLiteral(""));
        combo_T6s->setCheckable(true);
        combo_T5s = new QPushButton(WinSelectRange);
        combo_T5s->setObjectName(QStringLiteral("combo_T5s"));
        combo_T5s->setGeometry(QRect(325, 132, 34, 22));
        combo_T5s->setFont(font);
        combo_T5s->setStyleSheet(QStringLiteral(""));
        combo_T5s->setCheckable(true);
        combo_T4s = new QPushButton(WinSelectRange);
        combo_T4s->setObjectName(QStringLiteral("combo_T4s"));
        combo_T4s->setGeometry(QRect(360, 132, 33, 22));
        combo_T4s->setFont(font);
        combo_T4s->setStyleSheet(QStringLiteral(""));
        combo_T4s->setCheckable(true);
        combo_T3s = new QPushButton(WinSelectRange);
        combo_T3s->setObjectName(QStringLiteral("combo_T3s"));
        combo_T3s->setGeometry(QRect(394, 132, 34, 22));
        combo_T3s->setFont(font);
        combo_T3s->setStyleSheet(QStringLiteral(""));
        combo_T3s->setCheckable(true);
        combo_T2s = new QPushButton(WinSelectRange);
        combo_T2s->setObjectName(QStringLiteral("combo_T2s"));
        combo_T2s->setGeometry(QRect(429, 132, 33, 22));
        combo_T2s->setFont(font);
        combo_T2s->setStyleSheet(QStringLiteral(""));
        combo_T2s->setCheckable(true);
        combo_A9o = new QPushButton(WinSelectRange);
        combo_A9o->setObjectName(QStringLiteral("combo_A9o"));
        combo_A9o->setGeometry(QRect(13, 154, 34, 22));
        combo_A9o->setFont(font);
        combo_A9o->setStyleSheet(QStringLiteral(""));
        combo_A9o->setCheckable(true);
        combo_K9o = new QPushButton(WinSelectRange);
        combo_K9o->setObjectName(QStringLiteral("combo_K9o"));
        combo_K9o->setGeometry(QRect(48, 154, 34, 22));
        combo_K9o->setFont(font);
        combo_K9o->setStyleSheet(QStringLiteral(""));
        combo_K9o->setCheckable(true);
        combo_Q9o = new QPushButton(WinSelectRange);
        combo_Q9o->setObjectName(QStringLiteral("combo_Q9o"));
        combo_Q9o->setGeometry(QRect(83, 154, 33, 22));
        combo_Q9o->setFont(font);
        combo_Q9o->setStyleSheet(QStringLiteral(""));
        combo_Q9o->setCheckable(true);
        combo_J9o = new QPushButton(WinSelectRange);
        combo_J9o->setObjectName(QStringLiteral("combo_J9o"));
        combo_J9o->setGeometry(QRect(117, 154, 34, 22));
        combo_J9o->setFont(font);
        combo_J9o->setStyleSheet(QStringLiteral(""));
        combo_J9o->setCheckable(true);
        combo_T9o = new QPushButton(WinSelectRange);
        combo_T9o->setObjectName(QStringLiteral("combo_T9o"));
        combo_T9o->setGeometry(QRect(152, 154, 34, 22));
        combo_T9o->setFont(font);
        combo_T9o->setStyleSheet(QStringLiteral(""));
        combo_T9o->setCheckable(true);
        combo_99 = new QPushButton(WinSelectRange);
        combo_99->setObjectName(QStringLiteral("combo_99"));
        combo_99->setGeometry(QRect(187, 154, 33, 22));
        combo_99->setFont(font);
        combo_99->setAutoFillBackground(false);
        combo_99->setStyleSheet(QStringLiteral(""));
        combo_99->setCheckable(true);
        combo_98s = new QPushButton(WinSelectRange);
        combo_98s->setObjectName(QStringLiteral("combo_98s"));
        combo_98s->setGeometry(QRect(221, 154, 34, 22));
        combo_98s->setFont(font);
        combo_98s->setStyleSheet(QStringLiteral(""));
        combo_98s->setCheckable(true);
        combo_97s = new QPushButton(WinSelectRange);
        combo_97s->setObjectName(QStringLiteral("combo_97s"));
        combo_97s->setGeometry(QRect(256, 154, 33, 22));
        combo_97s->setFont(font);
        combo_97s->setStyleSheet(QStringLiteral(""));
        combo_97s->setCheckable(true);
        combo_96s = new QPushButton(WinSelectRange);
        combo_96s->setObjectName(QStringLiteral("combo_96s"));
        combo_96s->setGeometry(QRect(290, 154, 34, 22));
        combo_96s->setFont(font);
        combo_96s->setStyleSheet(QStringLiteral(""));
        combo_96s->setCheckable(true);
        combo_95s = new QPushButton(WinSelectRange);
        combo_95s->setObjectName(QStringLiteral("combo_95s"));
        combo_95s->setGeometry(QRect(325, 154, 34, 22));
        combo_95s->setFont(font);
        combo_95s->setStyleSheet(QStringLiteral(""));
        combo_95s->setCheckable(true);
        combo_94s = new QPushButton(WinSelectRange);
        combo_94s->setObjectName(QStringLiteral("combo_94s"));
        combo_94s->setGeometry(QRect(360, 154, 33, 22));
        combo_94s->setFont(font);
        combo_94s->setStyleSheet(QStringLiteral(""));
        combo_94s->setCheckable(true);
        combo_93s = new QPushButton(WinSelectRange);
        combo_93s->setObjectName(QStringLiteral("combo_93s"));
        combo_93s->setGeometry(QRect(394, 154, 34, 22));
        combo_93s->setFont(font);
        combo_93s->setStyleSheet(QStringLiteral(""));
        combo_93s->setCheckable(true);
        combo_92s = new QPushButton(WinSelectRange);
        combo_92s->setObjectName(QStringLiteral("combo_92s"));
        combo_92s->setGeometry(QRect(429, 154, 33, 22));
        combo_92s->setFont(font);
        combo_92s->setStyleSheet(QStringLiteral(""));
        combo_92s->setCheckable(true);
        combo_A8o = new QPushButton(WinSelectRange);
        combo_A8o->setObjectName(QStringLiteral("combo_A8o"));
        combo_A8o->setGeometry(QRect(13, 176, 34, 22));
        combo_A8o->setFont(font);
        combo_A8o->setStyleSheet(QStringLiteral(""));
        combo_A8o->setCheckable(true);
        combo_K8o = new QPushButton(WinSelectRange);
        combo_K8o->setObjectName(QStringLiteral("combo_K8o"));
        combo_K8o->setGeometry(QRect(48, 176, 34, 22));
        combo_K8o->setFont(font);
        combo_K8o->setStyleSheet(QStringLiteral(""));
        combo_K8o->setCheckable(true);
        combo_Q8o = new QPushButton(WinSelectRange);
        combo_Q8o->setObjectName(QStringLiteral("combo_Q8o"));
        combo_Q8o->setGeometry(QRect(83, 176, 33, 22));
        combo_Q8o->setFont(font);
        combo_Q8o->setStyleSheet(QStringLiteral(""));
        combo_Q8o->setCheckable(true);
        combo_J8o = new QPushButton(WinSelectRange);
        combo_J8o->setObjectName(QStringLiteral("combo_J8o"));
        combo_J8o->setGeometry(QRect(117, 176, 34, 22));
        combo_J8o->setFont(font);
        combo_J8o->setStyleSheet(QStringLiteral(""));
        combo_J8o->setCheckable(true);
        combo_T8o = new QPushButton(WinSelectRange);
        combo_T8o->setObjectName(QStringLiteral("combo_T8o"));
        combo_T8o->setGeometry(QRect(152, 176, 34, 22));
        combo_T8o->setFont(font);
        combo_T8o->setStyleSheet(QStringLiteral(""));
        combo_T8o->setCheckable(true);
        combo_98o = new QPushButton(WinSelectRange);
        combo_98o->setObjectName(QStringLiteral("combo_98o"));
        combo_98o->setGeometry(QRect(187, 176, 33, 22));
        combo_98o->setFont(font);
        combo_98o->setStyleSheet(QStringLiteral(""));
        combo_98o->setCheckable(true);
        combo_88 = new QPushButton(WinSelectRange);
        combo_88->setObjectName(QStringLiteral("combo_88"));
        combo_88->setGeometry(QRect(221, 176, 34, 22));
        sizePolicy.setHeightForWidth(combo_88->sizePolicy().hasHeightForWidth());
        combo_88->setSizePolicy(sizePolicy);
        combo_88->setFont(font);
        combo_88->setAutoFillBackground(false);
        combo_88->setStyleSheet(QStringLiteral(""));
        combo_88->setCheckable(true);
        combo_87s = new QPushButton(WinSelectRange);
        combo_87s->setObjectName(QStringLiteral("combo_87s"));
        combo_87s->setGeometry(QRect(256, 176, 33, 22));
        combo_87s->setFont(font);
        combo_87s->setStyleSheet(QStringLiteral(""));
        combo_87s->setCheckable(true);
        combo_86s = new QPushButton(WinSelectRange);
        combo_86s->setObjectName(QStringLiteral("combo_86s"));
        combo_86s->setGeometry(QRect(290, 176, 34, 22));
        combo_86s->setFont(font);
        combo_86s->setStyleSheet(QStringLiteral(""));
        combo_86s->setCheckable(true);
        combo_85s = new QPushButton(WinSelectRange);
        combo_85s->setObjectName(QStringLiteral("combo_85s"));
        combo_85s->setGeometry(QRect(325, 176, 34, 22));
        combo_85s->setFont(font);
        combo_85s->setStyleSheet(QStringLiteral(""));
        combo_85s->setCheckable(true);
        combo_84s = new QPushButton(WinSelectRange);
        combo_84s->setObjectName(QStringLiteral("combo_84s"));
        combo_84s->setGeometry(QRect(360, 176, 33, 22));
        combo_84s->setFont(font);
        combo_84s->setStyleSheet(QStringLiteral(""));
        combo_84s->setCheckable(true);
        combo_83s = new QPushButton(WinSelectRange);
        combo_83s->setObjectName(QStringLiteral("combo_83s"));
        combo_83s->setGeometry(QRect(394, 176, 34, 22));
        combo_83s->setFont(font);
        combo_83s->setStyleSheet(QStringLiteral(""));
        combo_83s->setCheckable(true);
        combo_82s = new QPushButton(WinSelectRange);
        combo_82s->setObjectName(QStringLiteral("combo_82s"));
        combo_82s->setGeometry(QRect(429, 176, 33, 22));
        combo_82s->setFont(font);
        combo_82s->setStyleSheet(QStringLiteral(""));
        combo_82s->setCheckable(true);
        combo_A7o = new QPushButton(WinSelectRange);
        combo_A7o->setObjectName(QStringLiteral("combo_A7o"));
        combo_A7o->setGeometry(QRect(13, 198, 34, 22));
        combo_A7o->setFont(font);
        combo_A7o->setStyleSheet(QStringLiteral(""));
        combo_A7o->setCheckable(true);
        combo_K7o = new QPushButton(WinSelectRange);
        combo_K7o->setObjectName(QStringLiteral("combo_K7o"));
        combo_K7o->setGeometry(QRect(48, 198, 34, 22));
        combo_K7o->setFont(font);
        combo_K7o->setStyleSheet(QStringLiteral(""));
        combo_K7o->setCheckable(true);
        combo_Q7o = new QPushButton(WinSelectRange);
        combo_Q7o->setObjectName(QStringLiteral("combo_Q7o"));
        combo_Q7o->setGeometry(QRect(83, 198, 33, 22));
        combo_Q7o->setFont(font);
        combo_Q7o->setStyleSheet(QStringLiteral(""));
        combo_Q7o->setCheckable(true);
        combo_J7o = new QPushButton(WinSelectRange);
        combo_J7o->setObjectName(QStringLiteral("combo_J7o"));
        combo_J7o->setGeometry(QRect(117, 198, 34, 22));
        combo_J7o->setFont(font);
        combo_J7o->setStyleSheet(QStringLiteral(""));
        combo_J7o->setCheckable(true);
        combo_T7o = new QPushButton(WinSelectRange);
        combo_T7o->setObjectName(QStringLiteral("combo_T7o"));
        combo_T7o->setGeometry(QRect(152, 198, 34, 22));
        combo_T7o->setFont(font);
        combo_T7o->setStyleSheet(QStringLiteral(""));
        combo_T7o->setCheckable(true);
        combo_97o = new QPushButton(WinSelectRange);
        combo_97o->setObjectName(QStringLiteral("combo_97o"));
        combo_97o->setGeometry(QRect(187, 198, 33, 22));
        combo_97o->setFont(font);
        combo_97o->setStyleSheet(QStringLiteral(""));
        combo_97o->setCheckable(true);
        combo_87o = new QPushButton(WinSelectRange);
        combo_87o->setObjectName(QStringLiteral("combo_87o"));
        combo_87o->setGeometry(QRect(221, 198, 34, 22));
        combo_87o->setFont(font);
        combo_87o->setStyleSheet(QStringLiteral(""));
        combo_87o->setCheckable(true);
        combo_77 = new QPushButton(WinSelectRange);
        combo_77->setObjectName(QStringLiteral("combo_77"));
        combo_77->setGeometry(QRect(256, 198, 33, 22));
        combo_77->setFont(font);
        combo_77->setAutoFillBackground(false);
        combo_77->setStyleSheet(QStringLiteral(""));
        combo_77->setCheckable(true);
        combo_76s = new QPushButton(WinSelectRange);
        combo_76s->setObjectName(QStringLiteral("combo_76s"));
        combo_76s->setGeometry(QRect(290, 198, 34, 22));
        combo_76s->setFont(font);
        combo_76s->setStyleSheet(QStringLiteral(""));
        combo_76s->setCheckable(true);
        combo_75s = new QPushButton(WinSelectRange);
        combo_75s->setObjectName(QStringLiteral("combo_75s"));
        combo_75s->setGeometry(QRect(325, 198, 34, 22));
        combo_75s->setFont(font);
        combo_75s->setStyleSheet(QStringLiteral(""));
        combo_75s->setCheckable(true);
        combo_74s = new QPushButton(WinSelectRange);
        combo_74s->setObjectName(QStringLiteral("combo_74s"));
        combo_74s->setGeometry(QRect(360, 198, 33, 22));
        combo_74s->setFont(font);
        combo_74s->setStyleSheet(QStringLiteral(""));
        combo_74s->setCheckable(true);
        combo_73s = new QPushButton(WinSelectRange);
        combo_73s->setObjectName(QStringLiteral("combo_73s"));
        combo_73s->setGeometry(QRect(394, 198, 34, 22));
        combo_73s->setFont(font);
        combo_73s->setStyleSheet(QStringLiteral(""));
        combo_73s->setCheckable(true);
        combo_72s = new QPushButton(WinSelectRange);
        combo_72s->setObjectName(QStringLiteral("combo_72s"));
        combo_72s->setGeometry(QRect(429, 198, 33, 22));
        combo_72s->setFont(font);
        combo_72s->setStyleSheet(QStringLiteral(""));
        combo_72s->setCheckable(true);
        combo_A6o = new QPushButton(WinSelectRange);
        combo_A6o->setObjectName(QStringLiteral("combo_A6o"));
        combo_A6o->setGeometry(QRect(13, 220, 34, 22));
        combo_A6o->setFont(font);
        combo_A6o->setStyleSheet(QStringLiteral(""));
        combo_A6o->setCheckable(true);
        combo_K6o = new QPushButton(WinSelectRange);
        combo_K6o->setObjectName(QStringLiteral("combo_K6o"));
        combo_K6o->setGeometry(QRect(48, 220, 34, 22));
        combo_K6o->setFont(font);
        combo_K6o->setStyleSheet(QStringLiteral(""));
        combo_K6o->setCheckable(true);
        combo_Q6o = new QPushButton(WinSelectRange);
        combo_Q6o->setObjectName(QStringLiteral("combo_Q6o"));
        combo_Q6o->setGeometry(QRect(83, 220, 33, 22));
        combo_Q6o->setFont(font);
        combo_Q6o->setStyleSheet(QStringLiteral(""));
        combo_Q6o->setCheckable(true);
        combo_J6o = new QPushButton(WinSelectRange);
        combo_J6o->setObjectName(QStringLiteral("combo_J6o"));
        combo_J6o->setGeometry(QRect(117, 220, 34, 22));
        combo_J6o->setFont(font);
        combo_J6o->setStyleSheet(QStringLiteral(""));
        combo_J6o->setCheckable(true);
        combo_T6o = new QPushButton(WinSelectRange);
        combo_T6o->setObjectName(QStringLiteral("combo_T6o"));
        combo_T6o->setGeometry(QRect(152, 220, 34, 22));
        combo_T6o->setFont(font);
        combo_T6o->setStyleSheet(QStringLiteral(""));
        combo_T6o->setCheckable(true);
        combo_96o = new QPushButton(WinSelectRange);
        combo_96o->setObjectName(QStringLiteral("combo_96o"));
        combo_96o->setGeometry(QRect(187, 220, 33, 22));
        combo_96o->setFont(font);
        combo_96o->setStyleSheet(QStringLiteral(""));
        combo_96o->setCheckable(true);
        combo_86o = new QPushButton(WinSelectRange);
        combo_86o->setObjectName(QStringLiteral("combo_86o"));
        combo_86o->setGeometry(QRect(221, 220, 34, 22));
        combo_86o->setFont(font);
        combo_86o->setStyleSheet(QStringLiteral(""));
        combo_86o->setCheckable(true);
        combo_76o = new QPushButton(WinSelectRange);
        combo_76o->setObjectName(QStringLiteral("combo_76o"));
        combo_76o->setGeometry(QRect(256, 220, 33, 22));
        combo_76o->setFont(font);
        combo_76o->setStyleSheet(QStringLiteral(""));
        combo_76o->setCheckable(true);
        combo_66 = new QPushButton(WinSelectRange);
        combo_66->setObjectName(QStringLiteral("combo_66"));
        combo_66->setGeometry(QRect(290, 220, 34, 22));
        combo_66->setFont(font);
        combo_66->setAutoFillBackground(false);
        combo_66->setStyleSheet(QStringLiteral(""));
        combo_66->setCheckable(true);
        combo_65s = new QPushButton(WinSelectRange);
        combo_65s->setObjectName(QStringLiteral("combo_65s"));
        combo_65s->setGeometry(QRect(325, 220, 34, 22));
        combo_65s->setFont(font);
        combo_65s->setStyleSheet(QStringLiteral(""));
        combo_65s->setCheckable(true);
        combo_64s = new QPushButton(WinSelectRange);
        combo_64s->setObjectName(QStringLiteral("combo_64s"));
        combo_64s->setGeometry(QRect(360, 220, 33, 22));
        combo_64s->setFont(font);
        combo_64s->setStyleSheet(QStringLiteral(""));
        combo_64s->setCheckable(true);
        combo_63s = new QPushButton(WinSelectRange);
        combo_63s->setObjectName(QStringLiteral("combo_63s"));
        combo_63s->setGeometry(QRect(394, 220, 34, 22));
        combo_63s->setFont(font);
        combo_63s->setStyleSheet(QStringLiteral(""));
        combo_63s->setCheckable(true);
        combo_62s = new QPushButton(WinSelectRange);
        combo_62s->setObjectName(QStringLiteral("combo_62s"));
        combo_62s->setGeometry(QRect(429, 220, 33, 22));
        combo_62s->setFont(font);
        combo_62s->setStyleSheet(QStringLiteral(""));
        combo_62s->setCheckable(true);
        combo_A5o = new QPushButton(WinSelectRange);
        combo_A5o->setObjectName(QStringLiteral("combo_A5o"));
        combo_A5o->setGeometry(QRect(13, 242, 34, 22));
        combo_A5o->setFont(font);
        combo_A5o->setStyleSheet(QStringLiteral(""));
        combo_A5o->setCheckable(true);
        combo_K5o = new QPushButton(WinSelectRange);
        combo_K5o->setObjectName(QStringLiteral("combo_K5o"));
        combo_K5o->setGeometry(QRect(48, 242, 34, 22));
        combo_K5o->setFont(font);
        combo_K5o->setStyleSheet(QStringLiteral(""));
        combo_K5o->setCheckable(true);
        combo_Q5o = new QPushButton(WinSelectRange);
        combo_Q5o->setObjectName(QStringLiteral("combo_Q5o"));
        combo_Q5o->setGeometry(QRect(83, 242, 33, 22));
        combo_Q5o->setFont(font);
        combo_Q5o->setStyleSheet(QStringLiteral(""));
        combo_Q5o->setCheckable(true);
        combo_J5o = new QPushButton(WinSelectRange);
        combo_J5o->setObjectName(QStringLiteral("combo_J5o"));
        combo_J5o->setGeometry(QRect(117, 242, 34, 22));
        combo_J5o->setFont(font);
        combo_J5o->setStyleSheet(QStringLiteral(""));
        combo_J5o->setCheckable(true);
        combo_T5o = new QPushButton(WinSelectRange);
        combo_T5o->setObjectName(QStringLiteral("combo_T5o"));
        combo_T5o->setGeometry(QRect(152, 242, 34, 22));
        combo_T5o->setFont(font);
        combo_T5o->setStyleSheet(QStringLiteral(""));
        combo_T5o->setCheckable(true);
        combo_95o = new QPushButton(WinSelectRange);
        combo_95o->setObjectName(QStringLiteral("combo_95o"));
        combo_95o->setGeometry(QRect(187, 242, 33, 22));
        combo_95o->setFont(font);
        combo_95o->setStyleSheet(QStringLiteral(""));
        combo_95o->setCheckable(true);
        combo_85o = new QPushButton(WinSelectRange);
        combo_85o->setObjectName(QStringLiteral("combo_85o"));
        combo_85o->setGeometry(QRect(221, 242, 34, 22));
        combo_85o->setFont(font);
        combo_85o->setStyleSheet(QStringLiteral(""));
        combo_85o->setCheckable(true);
        combo_75o = new QPushButton(WinSelectRange);
        combo_75o->setObjectName(QStringLiteral("combo_75o"));
        combo_75o->setGeometry(QRect(256, 242, 33, 22));
        combo_75o->setFont(font);
        combo_75o->setStyleSheet(QStringLiteral(""));
        combo_75o->setCheckable(true);
        combo_65o = new QPushButton(WinSelectRange);
        combo_65o->setObjectName(QStringLiteral("combo_65o"));
        combo_65o->setGeometry(QRect(290, 242, 34, 22));
        combo_65o->setFont(font);
        combo_65o->setStyleSheet(QStringLiteral(""));
        combo_65o->setCheckable(true);
        combo_55 = new QPushButton(WinSelectRange);
        combo_55->setObjectName(QStringLiteral("combo_55"));
        combo_55->setGeometry(QRect(325, 242, 34, 22));
        combo_55->setFont(font);
        combo_55->setAutoFillBackground(false);
        combo_55->setStyleSheet(QStringLiteral(""));
        combo_55->setCheckable(true);
        combo_54s = new QPushButton(WinSelectRange);
        combo_54s->setObjectName(QStringLiteral("combo_54s"));
        combo_54s->setGeometry(QRect(360, 242, 33, 22));
        combo_54s->setFont(font);
        combo_54s->setStyleSheet(QStringLiteral(""));
        combo_54s->setCheckable(true);
        combo_53s = new QPushButton(WinSelectRange);
        combo_53s->setObjectName(QStringLiteral("combo_53s"));
        combo_53s->setGeometry(QRect(394, 242, 34, 22));
        combo_53s->setFont(font);
        combo_53s->setStyleSheet(QStringLiteral(""));
        combo_53s->setCheckable(true);
        combo_52s = new QPushButton(WinSelectRange);
        combo_52s->setObjectName(QStringLiteral("combo_52s"));
        combo_52s->setGeometry(QRect(429, 242, 33, 22));
        combo_52s->setFont(font);
        combo_52s->setStyleSheet(QStringLiteral(""));
        combo_52s->setCheckable(true);
        combo_A4o = new QPushButton(WinSelectRange);
        combo_A4o->setObjectName(QStringLiteral("combo_A4o"));
        combo_A4o->setGeometry(QRect(13, 264, 34, 22));
        combo_A4o->setFont(font);
        combo_A4o->setStyleSheet(QStringLiteral(""));
        combo_A4o->setCheckable(true);
        combo_K4o = new QPushButton(WinSelectRange);
        combo_K4o->setObjectName(QStringLiteral("combo_K4o"));
        combo_K4o->setGeometry(QRect(48, 264, 34, 22));
        combo_K4o->setFont(font);
        combo_K4o->setStyleSheet(QStringLiteral(""));
        combo_K4o->setCheckable(true);
        combo_Q4o = new QPushButton(WinSelectRange);
        combo_Q4o->setObjectName(QStringLiteral("combo_Q4o"));
        combo_Q4o->setGeometry(QRect(83, 264, 33, 22));
        combo_Q4o->setFont(font);
        combo_Q4o->setStyleSheet(QStringLiteral(""));
        combo_Q4o->setCheckable(true);
        combo_J4o = new QPushButton(WinSelectRange);
        combo_J4o->setObjectName(QStringLiteral("combo_J4o"));
        combo_J4o->setGeometry(QRect(117, 264, 34, 22));
        combo_J4o->setFont(font);
        combo_J4o->setStyleSheet(QStringLiteral(""));
        combo_J4o->setCheckable(true);
        combo_T4o = new QPushButton(WinSelectRange);
        combo_T4o->setObjectName(QStringLiteral("combo_T4o"));
        combo_T4o->setGeometry(QRect(152, 264, 34, 22));
        combo_T4o->setFont(font);
        combo_T4o->setStyleSheet(QStringLiteral(""));
        combo_T4o->setCheckable(true);
        combo_94o = new QPushButton(WinSelectRange);
        combo_94o->setObjectName(QStringLiteral("combo_94o"));
        combo_94o->setGeometry(QRect(187, 264, 33, 22));
        combo_94o->setFont(font);
        combo_94o->setStyleSheet(QStringLiteral(""));
        combo_94o->setCheckable(true);
        combo_84o = new QPushButton(WinSelectRange);
        combo_84o->setObjectName(QStringLiteral("combo_84o"));
        combo_84o->setGeometry(QRect(221, 264, 34, 22));
        combo_84o->setFont(font);
        combo_84o->setStyleSheet(QStringLiteral(""));
        combo_84o->setCheckable(true);
        combo_74o = new QPushButton(WinSelectRange);
        combo_74o->setObjectName(QStringLiteral("combo_74o"));
        combo_74o->setGeometry(QRect(256, 264, 33, 22));
        combo_74o->setFont(font);
        combo_74o->setStyleSheet(QStringLiteral(""));
        combo_74o->setCheckable(true);
        combo_64o = new QPushButton(WinSelectRange);
        combo_64o->setObjectName(QStringLiteral("combo_64o"));
        combo_64o->setGeometry(QRect(290, 264, 34, 22));
        combo_64o->setFont(font);
        combo_64o->setStyleSheet(QStringLiteral(""));
        combo_64o->setCheckable(true);
        combo_54o = new QPushButton(WinSelectRange);
        combo_54o->setObjectName(QStringLiteral("combo_54o"));
        combo_54o->setGeometry(QRect(325, 264, 34, 22));
        combo_54o->setFont(font);
        combo_54o->setStyleSheet(QStringLiteral(""));
        combo_54o->setCheckable(true);
        combo_44 = new QPushButton(WinSelectRange);
        combo_44->setObjectName(QStringLiteral("combo_44"));
        combo_44->setGeometry(QRect(360, 264, 33, 22));
        combo_44->setFont(font);
        combo_44->setAutoFillBackground(false);
        combo_44->setStyleSheet(QStringLiteral(""));
        combo_44->setCheckable(true);
        combo_43s = new QPushButton(WinSelectRange);
        combo_43s->setObjectName(QStringLiteral("combo_43s"));
        combo_43s->setGeometry(QRect(394, 264, 34, 22));
        combo_43s->setFont(font);
        combo_43s->setStyleSheet(QStringLiteral(""));
        combo_43s->setCheckable(true);
        combo_42s = new QPushButton(WinSelectRange);
        combo_42s->setObjectName(QStringLiteral("combo_42s"));
        combo_42s->setGeometry(QRect(429, 264, 33, 22));
        combo_42s->setFont(font);
        combo_42s->setStyleSheet(QStringLiteral(""));
        combo_42s->setCheckable(true);
        combo_A3o = new QPushButton(WinSelectRange);
        combo_A3o->setObjectName(QStringLiteral("combo_A3o"));
        combo_A3o->setGeometry(QRect(13, 286, 34, 22));
        combo_A3o->setFont(font);
        combo_A3o->setStyleSheet(QStringLiteral(""));
        combo_A3o->setCheckable(true);
        combo_K3o = new QPushButton(WinSelectRange);
        combo_K3o->setObjectName(QStringLiteral("combo_K3o"));
        combo_K3o->setGeometry(QRect(48, 286, 34, 22));
        combo_K3o->setFont(font);
        combo_K3o->setStyleSheet(QStringLiteral(""));
        combo_K3o->setCheckable(true);
        combo_Q3o = new QPushButton(WinSelectRange);
        combo_Q3o->setObjectName(QStringLiteral("combo_Q3o"));
        combo_Q3o->setGeometry(QRect(83, 286, 33, 22));
        combo_Q3o->setFont(font);
        combo_Q3o->setStyleSheet(QStringLiteral(""));
        combo_Q3o->setCheckable(true);
        combo_J3o = new QPushButton(WinSelectRange);
        combo_J3o->setObjectName(QStringLiteral("combo_J3o"));
        combo_J3o->setGeometry(QRect(117, 286, 34, 22));
        combo_J3o->setFont(font);
        combo_J3o->setStyleSheet(QStringLiteral(""));
        combo_J3o->setCheckable(true);
        combo_T3o = new QPushButton(WinSelectRange);
        combo_T3o->setObjectName(QStringLiteral("combo_T3o"));
        combo_T3o->setGeometry(QRect(152, 286, 34, 22));
        combo_T3o->setFont(font);
        combo_T3o->setStyleSheet(QStringLiteral(""));
        combo_T3o->setCheckable(true);
        combo_93o = new QPushButton(WinSelectRange);
        combo_93o->setObjectName(QStringLiteral("combo_93o"));
        combo_93o->setGeometry(QRect(187, 286, 33, 22));
        combo_93o->setFont(font);
        combo_93o->setStyleSheet(QStringLiteral(""));
        combo_93o->setCheckable(true);
        combo_83o = new QPushButton(WinSelectRange);
        combo_83o->setObjectName(QStringLiteral("combo_83o"));
        combo_83o->setGeometry(QRect(221, 286, 34, 22));
        combo_83o->setFont(font);
        combo_83o->setStyleSheet(QStringLiteral(""));
        combo_83o->setCheckable(true);
        combo_73o = new QPushButton(WinSelectRange);
        combo_73o->setObjectName(QStringLiteral("combo_73o"));
        combo_73o->setGeometry(QRect(256, 286, 33, 22));
        combo_73o->setFont(font);
        combo_73o->setStyleSheet(QStringLiteral(""));
        combo_73o->setCheckable(true);
        combo_63o = new QPushButton(WinSelectRange);
        combo_63o->setObjectName(QStringLiteral("combo_63o"));
        combo_63o->setGeometry(QRect(290, 286, 34, 22));
        combo_63o->setFont(font);
        combo_63o->setStyleSheet(QStringLiteral(""));
        combo_63o->setCheckable(true);
        combo_53o = new QPushButton(WinSelectRange);
        combo_53o->setObjectName(QStringLiteral("combo_53o"));
        combo_53o->setGeometry(QRect(325, 286, 34, 22));
        combo_53o->setFont(font);
        combo_53o->setStyleSheet(QStringLiteral(""));
        combo_53o->setCheckable(true);
        combo_43o = new QPushButton(WinSelectRange);
        combo_43o->setObjectName(QStringLiteral("combo_43o"));
        combo_43o->setGeometry(QRect(360, 286, 33, 22));
        combo_43o->setFont(font);
        combo_43o->setStyleSheet(QStringLiteral(""));
        combo_43o->setCheckable(true);
        combo_33 = new QPushButton(WinSelectRange);
        combo_33->setObjectName(QStringLiteral("combo_33"));
        combo_33->setGeometry(QRect(394, 286, 34, 22));
        combo_33->setFont(font);
        combo_33->setAutoFillBackground(false);
        combo_33->setStyleSheet(QStringLiteral(""));
        combo_33->setCheckable(true);
        combo_32s = new QPushButton(WinSelectRange);
        combo_32s->setObjectName(QStringLiteral("combo_32s"));
        combo_32s->setGeometry(QRect(429, 286, 33, 22));
        combo_32s->setFont(font);
        combo_32s->setStyleSheet(QStringLiteral(""));
        combo_32s->setCheckable(true);
        combo_A2o = new QPushButton(WinSelectRange);
        combo_A2o->setObjectName(QStringLiteral("combo_A2o"));
        combo_A2o->setGeometry(QRect(13, 308, 34, 22));
        combo_A2o->setFont(font);
        combo_A2o->setStyleSheet(QStringLiteral(""));
        combo_A2o->setCheckable(true);
        combo_K2o = new QPushButton(WinSelectRange);
        combo_K2o->setObjectName(QStringLiteral("combo_K2o"));
        combo_K2o->setGeometry(QRect(48, 308, 34, 22));
        combo_K2o->setFont(font);
        combo_K2o->setStyleSheet(QStringLiteral(""));
        combo_K2o->setCheckable(true);
        combo_Q2o = new QPushButton(WinSelectRange);
        combo_Q2o->setObjectName(QStringLiteral("combo_Q2o"));
        combo_Q2o->setGeometry(QRect(83, 308, 33, 22));
        combo_Q2o->setFont(font);
        combo_Q2o->setStyleSheet(QStringLiteral(""));
        combo_Q2o->setCheckable(true);
        combo_J2o = new QPushButton(WinSelectRange);
        combo_J2o->setObjectName(QStringLiteral("combo_J2o"));
        combo_J2o->setGeometry(QRect(117, 308, 34, 22));
        combo_J2o->setFont(font);
        combo_J2o->setStyleSheet(QStringLiteral(""));
        combo_J2o->setCheckable(true);
        combo_T2o = new QPushButton(WinSelectRange);
        combo_T2o->setObjectName(QStringLiteral("combo_T2o"));
        combo_T2o->setGeometry(QRect(152, 308, 34, 22));
        combo_T2o->setFont(font);
        combo_T2o->setStyleSheet(QStringLiteral(""));
        combo_T2o->setCheckable(true);
        combo_92o = new QPushButton(WinSelectRange);
        combo_92o->setObjectName(QStringLiteral("combo_92o"));
        combo_92o->setGeometry(QRect(187, 308, 33, 22));
        combo_92o->setFont(font);
        combo_92o->setStyleSheet(QStringLiteral(""));
        combo_92o->setCheckable(true);
        combo_82o = new QPushButton(WinSelectRange);
        combo_82o->setObjectName(QStringLiteral("combo_82o"));
        combo_82o->setGeometry(QRect(221, 308, 34, 22));
        combo_82o->setFont(font);
        combo_82o->setStyleSheet(QStringLiteral(""));
        combo_82o->setCheckable(true);
        combo_72o = new QPushButton(WinSelectRange);
        combo_72o->setObjectName(QStringLiteral("combo_72o"));
        combo_72o->setGeometry(QRect(256, 308, 33, 22));
        combo_72o->setFont(font);
        combo_72o->setStyleSheet(QStringLiteral(""));
        combo_72o->setCheckable(true);
        combo_62o = new QPushButton(WinSelectRange);
        combo_62o->setObjectName(QStringLiteral("combo_62o"));
        combo_62o->setGeometry(QRect(290, 308, 34, 22));
        combo_62o->setFont(font);
        combo_62o->setStyleSheet(QStringLiteral(""));
        combo_62o->setCheckable(true);
        combo_52o = new QPushButton(WinSelectRange);
        combo_52o->setObjectName(QStringLiteral("combo_52o"));
        combo_52o->setGeometry(QRect(325, 308, 34, 22));
        combo_52o->setFont(font);
        combo_52o->setStyleSheet(QStringLiteral(""));
        combo_52o->setCheckable(true);
        combo_42o = new QPushButton(WinSelectRange);
        combo_42o->setObjectName(QStringLiteral("combo_42o"));
        combo_42o->setGeometry(QRect(360, 308, 33, 22));
        combo_42o->setFont(font);
        combo_42o->setStyleSheet(QStringLiteral(""));
        combo_42o->setCheckable(true);
        combo_32o = new QPushButton(WinSelectRange);
        combo_32o->setObjectName(QStringLiteral("combo_32o"));
        combo_32o->setGeometry(QRect(394, 308, 34, 22));
        combo_32o->setFont(font);
        combo_32o->setStyleSheet(QStringLiteral(""));
        combo_32o->setCheckable(true);
        combo_22 = new QPushButton(WinSelectRange);
        combo_22->setObjectName(QStringLiteral("combo_22"));
        combo_22->setGeometry(QRect(429, 308, 33, 22));
        combo_22->setFont(font);
        combo_22->setAutoFillBackground(false);
        combo_22->setStyleSheet(QStringLiteral(""));
        combo_22->setCheckable(true);
        chk_suit_selector = new QCheckBox(WinSelectRange);
        chk_suit_selector->setObjectName(QStringLiteral("chk_suit_selector"));
        chk_suit_selector->setGeometry(QRect(470, 130, 121, 20));
        chk_suit_selector->setFont(font);
        chk_suit_selector->setIconSize(QSize(30, 20));
        chk_suit_selector->setChecked(true);
        button_cancel = new QPushButton(WinSelectRange);
        button_cancel->setObjectName(QStringLiteral("button_cancel"));
        button_cancel->setGeometry(QRect(470, 279, 111, 23));
        label_2 = new QLabel(WinSelectRange);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(10, 20, 231, 16));
        suit_03 = new QPushButton(WinSelectRange);
        suit_03->setObjectName(QStringLiteral("suit_03"));
        suit_03->setEnabled(false);
        suit_03->setGeometry(QRect(470, 110, 30, 19));
        QIcon icon;
        icon.addFile(QStringLiteral(":/styles/icon_suit_03.png"), QSize(), QIcon::Normal, QIcon::Off);
        suit_03->setIcon(icon);
        suit_03->setIconSize(QSize(30, 20));
        suit_03->setCheckable(true);
        suit_03->setChecked(true);
        suit_20 = new QPushButton(WinSelectRange);
        suit_20->setObjectName(QStringLiteral("suit_20"));
        suit_20->setEnabled(false);
        suit_20->setGeometry(QRect(530, 50, 30, 20));
        QIcon icon1;
        icon1.addFile(QStringLiteral(":/styles/icon_suit_20.png"), QSize(), QIcon::Normal, QIcon::Off);
        suit_20->setIcon(icon1);
        suit_20->setIconSize(QSize(30, 20));
        suit_20->setCheckable(true);
        suit_20->setChecked(true);
        suit_22 = new QPushButton(WinSelectRange);
        suit_22->setObjectName(QStringLiteral("suit_22"));
        suit_22->setEnabled(false);
        suit_22->setGeometry(QRect(530, 90, 30, 20));
        QIcon icon2;
        icon2.addFile(QStringLiteral(":/styles/icon_suit_22.png"), QSize(), QIcon::Normal, QIcon::Off);
        suit_22->setIcon(icon2);
        suit_22->setIconSize(QSize(30, 20));
        suit_22->setCheckable(true);
        suit_22->setChecked(true);
        suit_21 = new QPushButton(WinSelectRange);
        suit_21->setObjectName(QStringLiteral("suit_21"));
        suit_21->setEnabled(false);
        suit_21->setGeometry(QRect(530, 70, 30, 20));
        QIcon icon3;
        icon3.addFile(QStringLiteral(":/styles/icon_suit_21.png"), QSize(), QIcon::Normal, QIcon::Off);
        suit_21->setIcon(icon3);
        suit_21->setIconSize(QSize(30, 20));
        suit_21->setCheckable(true);
        suit_21->setChecked(true);
        suit_30 = new QPushButton(WinSelectRange);
        suit_30->setObjectName(QStringLiteral("suit_30"));
        suit_30->setEnabled(false);
        suit_30->setGeometry(QRect(560, 50, 29, 20));
        QIcon icon4;
        icon4.addFile(QStringLiteral(":/styles/icon_suit_30.png"), QSize(), QIcon::Normal, QIcon::Off);
        suit_30->setIcon(icon4);
        suit_30->setIconSize(QSize(30, 20));
        suit_30->setCheckable(true);
        suit_30->setChecked(true);
        suit_11 = new QPushButton(WinSelectRange);
        suit_11->setObjectName(QStringLiteral("suit_11"));
        suit_11->setEnabled(false);
        suit_11->setGeometry(QRect(500, 70, 30, 20));
        QIcon icon5;
        icon5.addFile(QStringLiteral(":/styles/icon_suit_11.png"), QSize(), QIcon::Normal, QIcon::Off);
        suit_11->setIcon(icon5);
        suit_11->setIconSize(QSize(30, 20));
        suit_11->setCheckable(true);
        suit_11->setChecked(true);
        suit_10 = new QPushButton(WinSelectRange);
        suit_10->setObjectName(QStringLiteral("suit_10"));
        suit_10->setEnabled(false);
        suit_10->setGeometry(QRect(500, 50, 30, 20));
        QIcon icon6;
        icon6.addFile(QStringLiteral(":/styles/icon_suit_10.png"), QSize(), QIcon::Normal, QIcon::Off);
        suit_10->setIcon(icon6);
        suit_10->setIconSize(QSize(30, 20));
        suit_10->setCheckable(true);
        suit_10->setChecked(true);
        suit_12 = new QPushButton(WinSelectRange);
        suit_12->setObjectName(QStringLiteral("suit_12"));
        suit_12->setEnabled(false);
        suit_12->setGeometry(QRect(500, 90, 30, 20));
        QIcon icon7;
        icon7.addFile(QStringLiteral(":/styles/icon_suit_12.png"), QSize(), QIcon::Normal, QIcon::Off);
        suit_12->setIcon(icon7);
        suit_12->setIconSize(QSize(30, 20));
        suit_12->setCheckable(true);
        suit_12->setChecked(true);
        suit_00 = new QPushButton(WinSelectRange);
        suit_00->setObjectName(QStringLiteral("suit_00"));
        suit_00->setEnabled(false);
        suit_00->setGeometry(QRect(470, 50, 30, 20));
        QIcon icon8;
        icon8.addFile(QStringLiteral(":/styles/icon_suit_00.png"), QSize(), QIcon::Normal, QIcon::Off);
        suit_00->setIcon(icon8);
        suit_00->setIconSize(QSize(30, 20));
        suit_00->setCheckable(true);
        suit_00->setChecked(true);
        suit_01 = new QPushButton(WinSelectRange);
        suit_01->setObjectName(QStringLiteral("suit_01"));
        suit_01->setEnabled(false);
        suit_01->setGeometry(QRect(470, 70, 30, 20));
        QIcon icon9;
        icon9.addFile(QStringLiteral(":/styles/icon_suit_01.png"), QSize(), QIcon::Normal, QIcon::Off);
        suit_01->setIcon(icon9);
        suit_01->setIconSize(QSize(30, 20));
        suit_01->setCheckable(true);
        suit_01->setChecked(true);
        suit_32 = new QPushButton(WinSelectRange);
        suit_32->setObjectName(QStringLiteral("suit_32"));
        suit_32->setEnabled(false);
        suit_32->setGeometry(QRect(560, 90, 29, 20));
        QIcon icon10;
        icon10.addFile(QStringLiteral(":/styles/icon_suit_32.png"), QSize(), QIcon::Normal, QIcon::Off);
        suit_32->setIcon(icon10);
        suit_32->setIconSize(QSize(30, 20));
        suit_32->setCheckable(true);
        suit_32->setChecked(true);
        suit_31 = new QPushButton(WinSelectRange);
        suit_31->setObjectName(QStringLiteral("suit_31"));
        suit_31->setEnabled(false);
        suit_31->setGeometry(QRect(560, 70, 29, 20));
        QIcon icon11;
        icon11.addFile(QStringLiteral(":/styles/icon_suit_31.png"), QSize(), QIcon::Normal, QIcon::Off);
        suit_31->setIcon(icon11);
        suit_31->setIconSize(QSize(30, 20));
        suit_31->setCheckable(true);
        suit_31->setChecked(true);
        suit_02 = new QPushButton(WinSelectRange);
        suit_02->setObjectName(QStringLiteral("suit_02"));
        suit_02->setEnabled(false);
        suit_02->setGeometry(QRect(470, 90, 30, 20));
        QIcon icon12;
        icon12.addFile(QStringLiteral(":/styles/icon_suit_02.png"), QSize(), QIcon::Normal, QIcon::Off);
        suit_02->setIcon(icon12);
        suit_02->setIconSize(QSize(30, 20));
        suit_02->setCheckable(true);
        suit_02->setChecked(true);
        suit_13 = new QPushButton(WinSelectRange);
        suit_13->setObjectName(QStringLiteral("suit_13"));
        suit_13->setEnabled(false);
        suit_13->setGeometry(QRect(500, 110, 30, 19));
        QIcon icon13;
        icon13.addFile(QStringLiteral(":/styles/icon_suit_13.png"), QSize(), QIcon::Normal, QIcon::Off);
        suit_13->setIcon(icon13);
        suit_13->setIconSize(QSize(30, 20));
        suit_13->setCheckable(true);
        suit_13->setChecked(true);
        suit_33 = new QPushButton(WinSelectRange);
        suit_33->setObjectName(QStringLiteral("suit_33"));
        suit_33->setEnabled(false);
        suit_33->setGeometry(QRect(560, 110, 29, 19));
        QIcon icon14;
        icon14.addFile(QStringLiteral(":/styles/icon_suit_33.png"), QSize(), QIcon::Normal, QIcon::Off);
        suit_33->setIcon(icon14);
        suit_33->setIconSize(QSize(30, 20));
        suit_33->setCheckable(true);
        suit_33->setChecked(true);
        suit_23 = new QPushButton(WinSelectRange);
        suit_23->setObjectName(QStringLiteral("suit_23"));
        suit_23->setEnabled(false);
        suit_23->setGeometry(QRect(530, 110, 30, 19));
        QIcon icon15;
        icon15.addFile(QStringLiteral(":/styles/icon_suit_23.png"), QSize(), QIcon::Normal, QIcon::Off);
        suit_23->setIcon(icon15);
        suit_23->setIconSize(QSize(30, 20));
        suit_23->setCheckable(true);
        suit_23->setChecked(true);
        layoutWidget = new QWidget(WinSelectRange);
        layoutWidget->setObjectName(QStringLiteral("layoutWidget"));
        layoutWidget->setGeometry(QRect(342, 12, 121, 25));
        gridLayout = new QGridLayout(layoutWidget);
        gridLayout->setObjectName(QStringLiteral("gridLayout"));
        gridLayout->setHorizontalSpacing(2);
        gridLayout->setContentsMargins(0, 0, 0, 0);
        label_vpip = new QLabel(layoutWidget);
        label_vpip->setObjectName(QStringLiteral("label_vpip"));
        label_vpip->setFont(font);
        label_vpip->setIndent(0);

        gridLayout->addWidget(label_vpip, 0, 2, 1, 1);

        line_vpip = new QLineEdit(layoutWidget);
        line_vpip->setObjectName(QStringLiteral("line_vpip"));
        line_vpip->setFont(font);
        line_vpip->setInputMethodHints(Qt::ImhDigitsOnly);

        gridLayout->addWidget(line_vpip, 0, 4, 1, 1);

        label_pfr = new QLabel(layoutWidget);
        label_pfr->setObjectName(QStringLiteral("label_pfr"));
        label_pfr->setFont(font);

        gridLayout->addWidget(label_pfr, 0, 0, 1, 1);

        line_pfr = new QLineEdit(layoutWidget);
        line_pfr->setObjectName(QStringLiteral("line_pfr"));
        line_pfr->setFont(font);
        line_pfr->setInputMethodHints(Qt::ImhDigitsOnly);

        gridLayout->addWidget(line_pfr, 0, 1, 1, 1);


        retranslateUi(WinSelectRange);

        QMetaObject::connectSlotsByName(WinSelectRange);
    } // setupUi

    void retranslateUi(QDialog *WinSelectRange)
    {
        WinSelectRange->setWindowTitle(QApplication::translate("WinSelectRange", "Range creator - EQMain", Q_NULLPTR));
        button_ok->setText(QApplication::translate("WinSelectRange", "Ok", Q_NULLPTR));
        button_clear->setText(QApplication::translate("WinSelectRange", "Clear", Q_NULLPTR));
        combo_AA->setText(QApplication::translate("WinSelectRange", "AA", Q_NULLPTR));
        combo_AKs->setText(QApplication::translate("WinSelectRange", "AKs", Q_NULLPTR));
        combo_AQs->setText(QApplication::translate("WinSelectRange", "AQs", Q_NULLPTR));
        combo_AJs->setText(QApplication::translate("WinSelectRange", "AJs", Q_NULLPTR));
        combo_ATs->setText(QApplication::translate("WinSelectRange", "ATs", Q_NULLPTR));
        combo_A9s->setText(QApplication::translate("WinSelectRange", "A9s", Q_NULLPTR));
        combo_A8s->setText(QApplication::translate("WinSelectRange", "A8s", Q_NULLPTR));
        combo_A7s->setText(QApplication::translate("WinSelectRange", "A7s", Q_NULLPTR));
        combo_A6s->setText(QApplication::translate("WinSelectRange", "A6s", Q_NULLPTR));
        combo_A5s->setText(QApplication::translate("WinSelectRange", "A5s", Q_NULLPTR));
        combo_A4s->setText(QApplication::translate("WinSelectRange", "A4s", Q_NULLPTR));
        combo_A3s->setText(QApplication::translate("WinSelectRange", "A3s", Q_NULLPTR));
        combo_A2s->setText(QApplication::translate("WinSelectRange", "A2s", Q_NULLPTR));
        combo_AKo->setText(QApplication::translate("WinSelectRange", "AKo", Q_NULLPTR));
        combo_KK->setText(QApplication::translate("WinSelectRange", "KK", Q_NULLPTR));
        combo_KQs->setText(QApplication::translate("WinSelectRange", "KQs", Q_NULLPTR));
        combo_KJs->setText(QApplication::translate("WinSelectRange", "KJs", Q_NULLPTR));
        combo_KTs->setText(QApplication::translate("WinSelectRange", "KTs", Q_NULLPTR));
        combo_K9s->setText(QApplication::translate("WinSelectRange", "K9s", Q_NULLPTR));
        combo_K8s->setText(QApplication::translate("WinSelectRange", "K8s", Q_NULLPTR));
        combo_K7s->setText(QApplication::translate("WinSelectRange", "K7s", Q_NULLPTR));
        combo_K6s->setText(QApplication::translate("WinSelectRange", "K6s", Q_NULLPTR));
        combo_K5s->setText(QApplication::translate("WinSelectRange", "K5s", Q_NULLPTR));
        combo_K4s->setText(QApplication::translate("WinSelectRange", "K4s", Q_NULLPTR));
        combo_K3s->setText(QApplication::translate("WinSelectRange", "K3s", Q_NULLPTR));
        combo_K2s->setText(QApplication::translate("WinSelectRange", "K2s", Q_NULLPTR));
        combo_AQo->setText(QApplication::translate("WinSelectRange", "AQo", Q_NULLPTR));
        combo_KQo->setText(QApplication::translate("WinSelectRange", "KQo", Q_NULLPTR));
        combo_QQ->setText(QApplication::translate("WinSelectRange", "QQ", Q_NULLPTR));
        combo_QJs->setText(QApplication::translate("WinSelectRange", "QJs", Q_NULLPTR));
        combo_QTs->setText(QApplication::translate("WinSelectRange", "QTs", Q_NULLPTR));
        combo_Q9s->setText(QApplication::translate("WinSelectRange", "Q9s", Q_NULLPTR));
        combo_Q8s->setText(QApplication::translate("WinSelectRange", "Q8s", Q_NULLPTR));
        combo_Q7s->setText(QApplication::translate("WinSelectRange", "Q7s", Q_NULLPTR));
        combo_Q6s->setText(QApplication::translate("WinSelectRange", "Q6s", Q_NULLPTR));
        combo_Q5s->setText(QApplication::translate("WinSelectRange", "Q5s", Q_NULLPTR));
        combo_Q4s->setText(QApplication::translate("WinSelectRange", "Q4s", Q_NULLPTR));
        combo_Q3s->setText(QApplication::translate("WinSelectRange", "Q3s", Q_NULLPTR));
        combo_Q2s->setText(QApplication::translate("WinSelectRange", "Q2s", Q_NULLPTR));
        combo_AJo->setText(QApplication::translate("WinSelectRange", "AJo", Q_NULLPTR));
        combo_KJo->setText(QApplication::translate("WinSelectRange", "KJo", Q_NULLPTR));
        combo_QJo->setText(QApplication::translate("WinSelectRange", "QJo", Q_NULLPTR));
        combo_JJ->setText(QApplication::translate("WinSelectRange", "JJ", Q_NULLPTR));
        combo_JTs->setText(QApplication::translate("WinSelectRange", "JTs", Q_NULLPTR));
        combo_J9s->setText(QApplication::translate("WinSelectRange", "J9s", Q_NULLPTR));
        combo_J8s->setText(QApplication::translate("WinSelectRange", "J8s", Q_NULLPTR));
        combo_J7s->setText(QApplication::translate("WinSelectRange", "J7s", Q_NULLPTR));
        combo_J6s->setText(QApplication::translate("WinSelectRange", "J6s", Q_NULLPTR));
        combo_J5s->setText(QApplication::translate("WinSelectRange", "J5s", Q_NULLPTR));
        combo_J4s->setText(QApplication::translate("WinSelectRange", "J4s", Q_NULLPTR));
        combo_J3s->setText(QApplication::translate("WinSelectRange", "J3s", Q_NULLPTR));
        combo_J2s->setText(QApplication::translate("WinSelectRange", "J2s", Q_NULLPTR));
        combo_ATo->setText(QApplication::translate("WinSelectRange", "ATo", Q_NULLPTR));
        combo_KTo->setText(QApplication::translate("WinSelectRange", "KTo", Q_NULLPTR));
        combo_QTo->setText(QApplication::translate("WinSelectRange", "QTo", Q_NULLPTR));
        combo_JTo->setText(QApplication::translate("WinSelectRange", "JTo", Q_NULLPTR));
        combo_TT->setText(QApplication::translate("WinSelectRange", "TT", Q_NULLPTR));
        combo_T9s->setText(QApplication::translate("WinSelectRange", "T9s", Q_NULLPTR));
        combo_T8s->setText(QApplication::translate("WinSelectRange", "T8s", Q_NULLPTR));
        combo_T7s->setText(QApplication::translate("WinSelectRange", "T7s", Q_NULLPTR));
        combo_T6s->setText(QApplication::translate("WinSelectRange", "T6s", Q_NULLPTR));
        combo_T5s->setText(QApplication::translate("WinSelectRange", "T5s", Q_NULLPTR));
        combo_T4s->setText(QApplication::translate("WinSelectRange", "T4s", Q_NULLPTR));
        combo_T3s->setText(QApplication::translate("WinSelectRange", "T3s", Q_NULLPTR));
        combo_T2s->setText(QApplication::translate("WinSelectRange", "T2s", Q_NULLPTR));
        combo_A9o->setText(QApplication::translate("WinSelectRange", "A9o", Q_NULLPTR));
        combo_K9o->setText(QApplication::translate("WinSelectRange", "K9o", Q_NULLPTR));
        combo_Q9o->setText(QApplication::translate("WinSelectRange", "Q9o", Q_NULLPTR));
        combo_J9o->setText(QApplication::translate("WinSelectRange", "J9o", Q_NULLPTR));
        combo_T9o->setText(QApplication::translate("WinSelectRange", "T9o", Q_NULLPTR));
        combo_99->setText(QApplication::translate("WinSelectRange", "99", Q_NULLPTR));
        combo_98s->setText(QApplication::translate("WinSelectRange", "98s", Q_NULLPTR));
        combo_97s->setText(QApplication::translate("WinSelectRange", "97s", Q_NULLPTR));
        combo_96s->setText(QApplication::translate("WinSelectRange", "96s", Q_NULLPTR));
        combo_95s->setText(QApplication::translate("WinSelectRange", "95s", Q_NULLPTR));
        combo_94s->setText(QApplication::translate("WinSelectRange", "94s", Q_NULLPTR));
        combo_93s->setText(QApplication::translate("WinSelectRange", "93s", Q_NULLPTR));
        combo_92s->setText(QApplication::translate("WinSelectRange", "92s", Q_NULLPTR));
        combo_A8o->setText(QApplication::translate("WinSelectRange", "A8o", Q_NULLPTR));
        combo_K8o->setText(QApplication::translate("WinSelectRange", "K8o", Q_NULLPTR));
        combo_Q8o->setText(QApplication::translate("WinSelectRange", "Q8o", Q_NULLPTR));
        combo_J8o->setText(QApplication::translate("WinSelectRange", "J8o", Q_NULLPTR));
        combo_T8o->setText(QApplication::translate("WinSelectRange", "T8o", Q_NULLPTR));
        combo_98o->setText(QApplication::translate("WinSelectRange", "98o", Q_NULLPTR));
        combo_88->setText(QApplication::translate("WinSelectRange", "88", Q_NULLPTR));
        combo_87s->setText(QApplication::translate("WinSelectRange", "87s", Q_NULLPTR));
        combo_86s->setText(QApplication::translate("WinSelectRange", "86s", Q_NULLPTR));
        combo_85s->setText(QApplication::translate("WinSelectRange", "85s", Q_NULLPTR));
        combo_84s->setText(QApplication::translate("WinSelectRange", "84s", Q_NULLPTR));
        combo_83s->setText(QApplication::translate("WinSelectRange", "83s", Q_NULLPTR));
        combo_82s->setText(QApplication::translate("WinSelectRange", "82s", Q_NULLPTR));
        combo_A7o->setText(QApplication::translate("WinSelectRange", "A7o", Q_NULLPTR));
        combo_K7o->setText(QApplication::translate("WinSelectRange", "K7o", Q_NULLPTR));
        combo_Q7o->setText(QApplication::translate("WinSelectRange", "Q7o", Q_NULLPTR));
        combo_J7o->setText(QApplication::translate("WinSelectRange", "J7o", Q_NULLPTR));
        combo_T7o->setText(QApplication::translate("WinSelectRange", "T7o", Q_NULLPTR));
        combo_97o->setText(QApplication::translate("WinSelectRange", "97o", Q_NULLPTR));
        combo_87o->setText(QApplication::translate("WinSelectRange", "87o", Q_NULLPTR));
        combo_77->setText(QApplication::translate("WinSelectRange", "77", Q_NULLPTR));
        combo_76s->setText(QApplication::translate("WinSelectRange", "76s", Q_NULLPTR));
        combo_75s->setText(QApplication::translate("WinSelectRange", "75s", Q_NULLPTR));
        combo_74s->setText(QApplication::translate("WinSelectRange", "74s", Q_NULLPTR));
        combo_73s->setText(QApplication::translate("WinSelectRange", "73s", Q_NULLPTR));
        combo_72s->setText(QApplication::translate("WinSelectRange", "72s", Q_NULLPTR));
        combo_A6o->setText(QApplication::translate("WinSelectRange", "A6o", Q_NULLPTR));
        combo_K6o->setText(QApplication::translate("WinSelectRange", "K6o", Q_NULLPTR));
        combo_Q6o->setText(QApplication::translate("WinSelectRange", "Q6o", Q_NULLPTR));
        combo_J6o->setText(QApplication::translate("WinSelectRange", "J6o", Q_NULLPTR));
        combo_T6o->setText(QApplication::translate("WinSelectRange", "T6o", Q_NULLPTR));
        combo_96o->setText(QApplication::translate("WinSelectRange", "96o", Q_NULLPTR));
        combo_86o->setText(QApplication::translate("WinSelectRange", "86o", Q_NULLPTR));
        combo_76o->setText(QApplication::translate("WinSelectRange", "76o", Q_NULLPTR));
        combo_66->setText(QApplication::translate("WinSelectRange", "66", Q_NULLPTR));
        combo_65s->setText(QApplication::translate("WinSelectRange", "65s", Q_NULLPTR));
        combo_64s->setText(QApplication::translate("WinSelectRange", "64s", Q_NULLPTR));
        combo_63s->setText(QApplication::translate("WinSelectRange", "63s", Q_NULLPTR));
        combo_62s->setText(QApplication::translate("WinSelectRange", "62s", Q_NULLPTR));
        combo_A5o->setText(QApplication::translate("WinSelectRange", "A5o", Q_NULLPTR));
        combo_K5o->setText(QApplication::translate("WinSelectRange", "K5o", Q_NULLPTR));
        combo_Q5o->setText(QApplication::translate("WinSelectRange", "Q5o", Q_NULLPTR));
        combo_J5o->setText(QApplication::translate("WinSelectRange", "J5o", Q_NULLPTR));
        combo_T5o->setText(QApplication::translate("WinSelectRange", "T5o", Q_NULLPTR));
        combo_95o->setText(QApplication::translate("WinSelectRange", "95o", Q_NULLPTR));
        combo_85o->setText(QApplication::translate("WinSelectRange", "85o", Q_NULLPTR));
        combo_75o->setText(QApplication::translate("WinSelectRange", "75o", Q_NULLPTR));
        combo_65o->setText(QApplication::translate("WinSelectRange", "65o", Q_NULLPTR));
        combo_55->setText(QApplication::translate("WinSelectRange", "55", Q_NULLPTR));
        combo_54s->setText(QApplication::translate("WinSelectRange", "54s", Q_NULLPTR));
        combo_53s->setText(QApplication::translate("WinSelectRange", "53s", Q_NULLPTR));
        combo_52s->setText(QApplication::translate("WinSelectRange", "52s", Q_NULLPTR));
        combo_A4o->setText(QApplication::translate("WinSelectRange", "A4o", Q_NULLPTR));
        combo_K4o->setText(QApplication::translate("WinSelectRange", "K4o", Q_NULLPTR));
        combo_Q4o->setText(QApplication::translate("WinSelectRange", "Q4o", Q_NULLPTR));
        combo_J4o->setText(QApplication::translate("WinSelectRange", "J4o", Q_NULLPTR));
        combo_T4o->setText(QApplication::translate("WinSelectRange", "T4o", Q_NULLPTR));
        combo_94o->setText(QApplication::translate("WinSelectRange", "94o", Q_NULLPTR));
        combo_84o->setText(QApplication::translate("WinSelectRange", "84o", Q_NULLPTR));
        combo_74o->setText(QApplication::translate("WinSelectRange", "74o", Q_NULLPTR));
        combo_64o->setText(QApplication::translate("WinSelectRange", "64o", Q_NULLPTR));
        combo_54o->setText(QApplication::translate("WinSelectRange", "54o", Q_NULLPTR));
        combo_44->setText(QApplication::translate("WinSelectRange", "44", Q_NULLPTR));
        combo_43s->setText(QApplication::translate("WinSelectRange", "43s", Q_NULLPTR));
        combo_42s->setText(QApplication::translate("WinSelectRange", "42s", Q_NULLPTR));
        combo_A3o->setText(QApplication::translate("WinSelectRange", "A3o", Q_NULLPTR));
        combo_K3o->setText(QApplication::translate("WinSelectRange", "K3o", Q_NULLPTR));
        combo_Q3o->setText(QApplication::translate("WinSelectRange", "Q3o", Q_NULLPTR));
        combo_J3o->setText(QApplication::translate("WinSelectRange", "J3o", Q_NULLPTR));
        combo_T3o->setText(QApplication::translate("WinSelectRange", "T3o", Q_NULLPTR));
        combo_93o->setText(QApplication::translate("WinSelectRange", "93o", Q_NULLPTR));
        combo_83o->setText(QApplication::translate("WinSelectRange", "83o", Q_NULLPTR));
        combo_73o->setText(QApplication::translate("WinSelectRange", "73o", Q_NULLPTR));
        combo_63o->setText(QApplication::translate("WinSelectRange", "63o", Q_NULLPTR));
        combo_53o->setText(QApplication::translate("WinSelectRange", "53o", Q_NULLPTR));
        combo_43o->setText(QApplication::translate("WinSelectRange", "43o", Q_NULLPTR));
        combo_33->setText(QApplication::translate("WinSelectRange", "33", Q_NULLPTR));
        combo_32s->setText(QApplication::translate("WinSelectRange", "32s", Q_NULLPTR));
        combo_A2o->setText(QApplication::translate("WinSelectRange", "A2o", Q_NULLPTR));
        combo_K2o->setText(QApplication::translate("WinSelectRange", "K2o", Q_NULLPTR));
        combo_Q2o->setText(QApplication::translate("WinSelectRange", "Q2o", Q_NULLPTR));
        combo_J2o->setText(QApplication::translate("WinSelectRange", "J2o", Q_NULLPTR));
        combo_T2o->setText(QApplication::translate("WinSelectRange", "T2o", Q_NULLPTR));
        combo_92o->setText(QApplication::translate("WinSelectRange", "92o", Q_NULLPTR));
        combo_82o->setText(QApplication::translate("WinSelectRange", "82o", Q_NULLPTR));
        combo_72o->setText(QApplication::translate("WinSelectRange", "72o", Q_NULLPTR));
        combo_62o->setText(QApplication::translate("WinSelectRange", "62o", Q_NULLPTR));
        combo_52o->setText(QApplication::translate("WinSelectRange", "52o", Q_NULLPTR));
        combo_42o->setText(QApplication::translate("WinSelectRange", "42o", Q_NULLPTR));
        combo_32o->setText(QApplication::translate("WinSelectRange", "32o", Q_NULLPTR));
        combo_22->setText(QApplication::translate("WinSelectRange", "22", Q_NULLPTR));
        chk_suit_selector->setText(QApplication::translate("WinSelectRange", "Mark all suits", Q_NULLPTR));
        button_cancel->setText(QApplication::translate("WinSelectRange", "Cancel", Q_NULLPTR));
        label_2->setText(QApplication::translate("WinSelectRange", "Select the combos for make the range", Q_NULLPTR));
        suit_03->setText(QString());
        suit_20->setText(QString());
        suit_22->setText(QString());
        suit_21->setText(QString());
        suit_30->setText(QString());
        suit_11->setText(QString());
        suit_10->setText(QString());
        suit_12->setText(QString());
        suit_00->setText(QString());
#ifndef QT_NO_SHORTCUT
        suit_00->setShortcut(QApplication::translate("WinSelectRange", "Ctrl+S", Q_NULLPTR));
#endif // QT_NO_SHORTCUT
        suit_01->setText(QString());
        suit_32->setText(QString());
        suit_31->setText(QString());
        suit_02->setText(QString());
        suit_13->setText(QString());
        suit_33->setText(QString());
        suit_23->setText(QString());
        label_vpip->setText(QApplication::translate("WinSelectRange", "<html><head/><body><p align=\"justify\">VPIP:</p></body></html>", Q_NULLPTR));
        line_vpip->setText(QApplication::translate("WinSelectRange", "0", Q_NULLPTR));
        label_pfr->setText(QApplication::translate("WinSelectRange", "<html><head/><body><p align=\"right\">PFR:</p></body></html>", Q_NULLPTR));
        line_pfr->setText(QApplication::translate("WinSelectRange", "0", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class WinSelectRange: public Ui_WinSelectRange {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_WINSELECTRANGE_H
